/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */
/* faltan las funciones round,floor,ceiling,min,max,iif */

package com.soin.rh.calculo;

public interface CalculatorConstants {

  int EOF = 0;
  int BOOLEAN = 3;
  int DATE = 4;
  int NUMBER = 5;
  int FUNCTION = 6;
  int IDENTIFIER = 7;
  int STMTSEPARATOR = 8;
  int DIGIT = 9;
  int LETTER = 10;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<BOOLEAN>",
    "<DATE>",
    "<NUMBER>",
    "<FUNCTION>",
    "<IDENTIFIER>",
    "<STMTSEPARATOR>",
    "<DIGIT>",
    "<LETTER>",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"?\"",
    "\":\"",
    "\"||\"",
    "\"|\"",
    "\"&&\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
