<cfinvoke component="sif.Componentes.pListas" method="pLista"
	tabla="OBtipoProyecto"
	columnas="OBTPid,OBTPcodigo,OBTPdescripcion"
	filtro="Ecodigo=#session.Ecodigo# order by OBTPcodigo,OBTPdescripcion"
	desplegar="OBTPcodigo,OBTPdescripcion"
	etiquetas="Codigo,Descripcion de Tipo Proyecto"
	formatos="S,S"
	align="left,left"
	ira="OBtipoProyecto.cfm"
	form_method="post"
	keys="OBTPid"
	mostrar_filtro="yes"
	filtrar_automatico="yes"
	botones="Nuevo"
/>
