/*
 * Generated by JasperReports - 04/01/05 04:18 PM
 */
import dori.jasper.engine.*;
import dori.jasper.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class classic extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_Ecodigo = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_id_centro = null;
    private JRFillParameter parameter_RHEEid = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;

    private JRFillField field_RHNEDnotajefe = null;
    private JRFillField field_cedula = null;
    private JRFillField field_Edescripcion = null;
    private JRFillField field_NombreJefe = null;
    private JRFillField field_RHNEDnotaauto = null;
    private JRFillField field_RHNEDpromedio = null;
    private JRFillField field_CFdescripcion = null;
    private JRFillField field_RHEEdescripcion = null;
    private JRFillField field_RHHdescripcion = null;
    private JRFillField field_RHNEDpromotros = null;
    private JRFillField field_NombreEmpleado = null;
    private JRFillField field_Habilidad = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_test = null;
    private JRFillVariable variable_Empleado_COUNT = null;
    private JRFillVariable variable_RHHdescripcion_COUNT = null;
    private JRFillVariable variable_CFdescripcion_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_Ecodigo = (JRFillParameter)parsm.get("Ecodigo");
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_id_centro = (JRFillParameter)parsm.get("id_centro");
        parameter_RHEEid = (JRFillParameter)parsm.get("RHEEid");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");

        field_RHNEDnotajefe = (JRFillField)fldsm.get("RHNEDnotajefe");
        field_cedula = (JRFillField)fldsm.get("cedula");
        field_Edescripcion = (JRFillField)fldsm.get("Edescripcion");
        field_NombreJefe = (JRFillField)fldsm.get("NombreJefe");
        field_RHNEDnotaauto = (JRFillField)fldsm.get("RHNEDnotaauto");
        field_RHNEDpromedio = (JRFillField)fldsm.get("RHNEDpromedio");
        field_CFdescripcion = (JRFillField)fldsm.get("CFdescripcion");
        field_RHEEdescripcion = (JRFillField)fldsm.get("RHEEdescripcion");
        field_RHHdescripcion = (JRFillField)fldsm.get("RHHdescripcion");
        field_RHNEDpromotros = (JRFillField)fldsm.get("RHNEDpromotros");
        field_NombreEmpleado = (JRFillField)fldsm.get("NombreEmpleado");
        field_Habilidad = (JRFillField)fldsm.get("Habilidad");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_test = (JRFillVariable)varsm.get("test");
        variable_Empleado_COUNT = (JRFillVariable)varsm.get("Empleado_COUNT");
        variable_RHHdescripcion_COUNT = (JRFillVariable)varsm.get("RHHdescripcion_COUNT");
        variable_CFdescripcion_COUNT = (JRFillVariable)varsm.get("CFdescripcion_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 162 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 131 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 139 : // variableInitialValue_Empleado_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 127 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 147 : // variable_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 118 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 157 : // textField_9
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDnotaauto.getValue()));
                break;
            }
            case 120 : // parameterDefaultValue_RHEEid
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(26));
                break;
            }
            case 124 : // group_Empleado
            {
                value = (java.lang.Object)(((java.lang.String)field_cedula.getValue()));
                break;
            }
            case 143 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_RHHdescripcion.getValue()));
                break;
            }
            case 117 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 123 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 154 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_RHEEdescripcion.getValue()));
                break;
            }
            case 163 : // textField_13
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " de ");
                break;
            }
            case 142 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 133 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_cedula.getValue()));
                break;
            }
            case 161 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 128 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 141 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 155 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 126 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 115 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 158 : // textField_10
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDnotajefe.getValue()));
                break;
            }
            case 164 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 160 : // textField_12
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDpromedio.getValue()));
                break;
            }
            case 149 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 134 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 156 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_Habilidad.getValue()));
                break;
            }
            case 144 : // variable_RHHdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 136 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 112 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 145 : // variableInitialValue_RHHdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 146 : // group_CFdescripcion
            {
                value = (java.lang.Object)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 137 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 132 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_NombreEmpleado.getValue()));
                break;
            }
            case 151 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 167 : // textField_15
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 114 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 140 : // group_RHHdescripcion
            {
                value = (java.lang.Object)(((java.lang.String)field_RHHdescripcion.getValue()));
                break;
            }
            case 129 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_NombreJefe.getValue()));
                break;
            }
            case 153 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 138 : // variable_Empleado_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 148 : // variableInitialValue_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 113 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 152 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 125 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 116 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 166 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 121 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(28));
                break;
            }
            case 135 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 150 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) == null));
                break;
            }
            case 165 : // textField_14
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 122 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 119 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 159 : // textField_11
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDpromotros.getValue()));
                break;
            }
            case 130 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 162 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 131 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 139 : // variableInitialValue_Empleado_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 127 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getOldValue()));
                break;
            }
            case 147 : // variable_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 118 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 157 : // textField_9
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDnotaauto.getOldValue()));
                break;
            }
            case 120 : // parameterDefaultValue_RHEEid
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(26));
                break;
            }
            case 124 : // group_Empleado
            {
                value = (java.lang.Object)(((java.lang.String)field_cedula.getOldValue()));
                break;
            }
            case 143 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_RHHdescripcion.getOldValue()));
                break;
            }
            case 117 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 123 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 154 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_RHEEdescripcion.getOldValue()));
                break;
            }
            case 163 : // textField_13
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " de ");
                break;
            }
            case 142 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 133 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_cedula.getOldValue()));
                break;
            }
            case 161 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 128 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 141 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 155 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 126 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 115 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 158 : // textField_10
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDnotajefe.getOldValue()));
                break;
            }
            case 164 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 160 : // textField_12
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDpromedio.getOldValue()));
                break;
            }
            case 149 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 134 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 156 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_Habilidad.getOldValue()));
                break;
            }
            case 144 : // variable_RHHdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 136 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 112 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 145 : // variableInitialValue_RHHdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 146 : // group_CFdescripcion
            {
                value = (java.lang.Object)(((java.lang.String)field_CFdescripcion.getOldValue()));
                break;
            }
            case 137 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 132 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_NombreEmpleado.getOldValue()));
                break;
            }
            case 151 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 167 : // textField_15
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 114 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 140 : // group_RHHdescripcion
            {
                value = (java.lang.Object)(((java.lang.String)field_RHHdescripcion.getOldValue()));
                break;
            }
            case 129 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_NombreJefe.getOldValue()));
                break;
            }
            case 153 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 138 : // variable_Empleado_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 148 : // variableInitialValue_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 113 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 152 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getOldValue()));
                break;
            }
            case 125 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 116 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 166 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 121 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(28));
                break;
            }
            case 135 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 150 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) == null));
                break;
            }
            case 165 : // textField_14
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 122 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 119 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 159 : // textField_11
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDpromotros.getOldValue()));
                break;
            }
            case 130 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 162 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 131 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 139 : // variableInitialValue_Empleado_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 127 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 147 : // variable_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 118 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 157 : // textField_9
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDnotaauto.getValue()));
                break;
            }
            case 120 : // parameterDefaultValue_RHEEid
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(26));
                break;
            }
            case 124 : // group_Empleado
            {
                value = (java.lang.Object)(((java.lang.String)field_cedula.getValue()));
                break;
            }
            case 143 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_RHHdescripcion.getValue()));
                break;
            }
            case 117 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 123 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 154 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_RHEEdescripcion.getValue()));
                break;
            }
            case 163 : // textField_13
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " de ");
                break;
            }
            case 142 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 133 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_cedula.getValue()));
                break;
            }
            case 161 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 128 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 141 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 155 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 126 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 115 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 158 : // textField_10
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDnotajefe.getValue()));
                break;
            }
            case 164 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 160 : // textField_12
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDpromedio.getValue()));
                break;
            }
            case 149 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 134 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 156 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_Habilidad.getValue()));
                break;
            }
            case 144 : // variable_RHHdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 136 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 112 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 145 : // variableInitialValue_RHHdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 146 : // group_CFdescripcion
            {
                value = (java.lang.Object)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 137 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 132 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_NombreEmpleado.getValue()));
                break;
            }
            case 151 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 167 : // textField_15
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 114 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 140 : // group_RHHdescripcion
            {
                value = (java.lang.Object)(((java.lang.String)field_RHHdescripcion.getValue()));
                break;
            }
            case 129 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_NombreJefe.getValue()));
                break;
            }
            case 153 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 138 : // variable_Empleado_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 148 : // variableInitialValue_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 113 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 152 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 125 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 116 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 166 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 121 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(28));
                break;
            }
            case 135 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 150 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) == null));
                break;
            }
            case 165 : // textField_14
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 122 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 119 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 159 : // textField_11
            {
                value = (java.lang.Double)(((java.lang.Double)field_RHNEDpromotros.getValue()));
                break;
            }
            case 130 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
