'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
'
Namespace DBmodel
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WS.cfcSoapBinding", [Namespace]:="http://componentes.dbmodel.parches.asp"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Map)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(QueryBean)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(CFCInvocationException))>  _
    Partial Public Class WSService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private uploadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private addModeloOperationCompleted As System.Threading.SendOrPostCallback
        
        Private qryEsquemasModeloOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.PDtoCF.My.MySettings.Default.PowerDesignerTOColdFusion_DBmodel_WSService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event uploadCompleted As uploadCompletedEventHandler
        
        '''<remarks/>
        Public Event addModeloCompleted As addModeloCompletedEventHandler
        
        '''<remarks/>
        Public Event qryEsquemasModeloCompleted As qryEsquemasModeloCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://componentes.dbmodel.parches.asp", ResponseNamespace:="http://componentes.dbmodel.parches.asp")>  _
        Public Function upload(ByVal usuario As String, ByVal modelo As String, ByVal descripcion As String, ByVal cantidad As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")> ByVal XMLzip() As Byte) As <System.Xml.Serialization.SoapElementAttribute("uploadReturn")> String
            Dim results() As Object = Me.Invoke("upload", New Object() {usuario, modelo, descripcion, cantidad, XMLzip})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub uploadAsync(ByVal usuario As String, ByVal modelo As String, ByVal descripcion As String, ByVal cantidad As String, ByVal XMLzip() As Byte)
            Me.uploadAsync(usuario, modelo, descripcion, cantidad, XMLzip, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub uploadAsync(ByVal usuario As String, ByVal modelo As String, ByVal descripcion As String, ByVal cantidad As String, ByVal XMLzip() As Byte, ByVal userState As Object)
            If (Me.uploadOperationCompleted Is Nothing) Then
                Me.uploadOperationCompleted = AddressOf Me.OnuploadOperationCompleted
            End If
            Me.InvokeAsync("upload", New Object() {usuario, modelo, descripcion, cantidad, XMLzip}, Me.uploadOperationCompleted, userState)
        End Sub
        
        Private Sub OnuploadOperationCompleted(ByVal arg As Object)
            If (Not (Me.uploadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent uploadCompleted(Me, New uploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://componentes.dbmodel.parches.asp", ResponseNamespace:="http://componentes.dbmodel.parches.asp")>  _
        Public Sub addModelo(ByVal modelo As String, ByVal esquema As String, ByVal usuario As String)
            Me.Invoke("addModelo", New Object() {modelo, esquema, usuario})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub addModeloAsync(ByVal modelo As String, ByVal esquema As String, ByVal usuario As String)
            Me.addModeloAsync(modelo, esquema, usuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub addModeloAsync(ByVal modelo As String, ByVal esquema As String, ByVal usuario As String, ByVal userState As Object)
            If (Me.addModeloOperationCompleted Is Nothing) Then
                Me.addModeloOperationCompleted = AddressOf Me.OnaddModeloOperationCompleted
            End If
            Me.InvokeAsync("addModelo", New Object() {modelo, esquema, usuario}, Me.addModeloOperationCompleted, userState)
        End Sub
        
        Private Sub OnaddModeloOperationCompleted(ByVal arg As Object)
            If (Not (Me.addModeloCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent addModeloCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://componentes.dbmodel.parches.asp", ResponseNamespace:="http://componentes.dbmodel.parches.asp")>  _
        Public Function qryEsquemasModelo(ByVal modelo As String) As <System.Xml.Serialization.SoapElementAttribute("qryEsquemasModeloReturn")> Object()
            Dim results() As Object = Me.Invoke("qryEsquemasModelo", New Object() {modelo})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub qryEsquemasModeloAsync(ByVal modelo As String)
            Me.qryEsquemasModeloAsync(modelo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub qryEsquemasModeloAsync(ByVal modelo As String, ByVal userState As Object)
            If (Me.qryEsquemasModeloOperationCompleted Is Nothing) Then
                Me.qryEsquemasModeloOperationCompleted = AddressOf Me.OnqryEsquemasModeloOperationCompleted
            End If
            Me.InvokeAsync("qryEsquemasModelo", New Object() {modelo}, Me.qryEsquemasModeloOperationCompleted, userState)
        End Sub
        
        Private Sub OnqryEsquemasModeloOperationCompleted(ByVal arg As Object)
            If (Not (Me.qryEsquemasModeloCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent qryEsquemasModeloCompleted(Me, New qryEsquemasModeloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://xml.apache.org/xml-soap")>  _
    Partial Public Class Map
        
        Private itemField() As mapItem
        
        '''<remarks/>
        Public Property item() As mapItem()
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://xml.apache.org/xml-soap")>  _
    Partial Public Class mapItem
        
        Private keyField As Object
        
        Private valueField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property key() As Object
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://rpc.xml.coldfusion")>  _
    Partial Public Class QueryBean
        
        Private columnListField() As String
        
        Private dataField() As Object
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property columnList() As String()
            Get
                Return Me.columnListField
            End Get
            Set
                Me.columnListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property data() As Object()
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://rpc.xml.coldfusion")>  _
    Partial Public Class CFCInvocationException
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub uploadCompletedEventHandler(ByVal sender As Object, ByVal e As uploadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class uploadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub addModeloCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub qryEsquemasModeloCompletedEventHandler(ByVal sender As Object, ByVal e As qryEsquemasModeloCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class qryEsquemasModeloCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
End Namespace
