<p align="CENTER"> <b>Lo que usted debe saber al ingresar al portal</b> </p>
<p align="JUSTIFY">
Gracias por visitar nuestro portal. Por favor lea
cuidadosamente estos t&eacute;rminos y condiciones. Si
luego de leerlos est&aacute; de acuerdo, oprima el comando
de ACEPTAR al pie de esta p&aacute;gina. Podr&aacute;
entonces obtener su identificaci&oacute;n personal y su
clave de acceso permanente. Una vez completado ese paso, su
identificaci&oacute;n personal y clave de acceso temporales
quedar&aacute;n desactivadas y usted queda expresamente
obligado a guardar el secreto de la nueva
identificaci&oacute;n personal y clave de acceso
permanente, y queda sujeto a las limitaciones de
responsabilidad y a las disposiciones legales y
contractuales entre el usuario y el administrador del
portal, que a continuaci&oacute;n se describen.
</p>
<p align="JUSTIFY">
Si no esta de acuerdo con los t&eacute;rminos y
condiciones, oprima el comando de NO ACEPTAR al pie de esta
p&aacute;gina, para no ingresar al portal y regresar a la
pagina anterior.
</p>
<p align="JUSTIFY">
 
</p>
<p align="CENTER">
<b>DEFINICIONES</b>
</p>
<p align="JUSTIFY">
Las siguientes son definiciones de algunos vocablos que se
utilizan en esta p&aacute;gina para definir los
t&eacute;rminos y condiciones de uso de este portal.
</p>
<p align="JUSTIFY">
<u>USUARIO</u>: La persona que solicita obtener acceso a
este portal y provee toda la informaci&oacute;n necesaria
para obtener la identificaci&oacute;n personal y palabra
clave de acceso al portal, temporal y permanente.
</p>
<p align="JUSTIFY">
<u>ADMINISTRADOR DEL PORTAL</u>: La compa&ntilde;&iacute;a
propietaria que opera y administra el portal,
SOIN-SOLUCIONES INTEGRALES S.A.
</p>
<p align="JUSTIFY">
<u>PORTAL:</u> Es el sitio interactivo en la red Internet
denominado "migestion.net - Expediente Estudiantil",
dise&ntilde;ado y operado por el administrador del portal.
</p>
<p align="JUSTIFY">
<u>PARTICIPANTE O PARTICIPANTES</u>: Las instituciones de
gobierno e instituciones aut&oacute;nomas, y centros
educativos p&uacute;blicos y privados.
</p>
<p align="JUSTIFY">
<u>TERCEROS</u>: Otros individuos o personas
jur&iacute;dicas ajenas al usuario y al administrador
</p>
<p align="JUSTIFY">
del portal.
</p>
<p align="JUSTIFY">
 
</p>
<p align="CENTER">
<b>TERMINOS Y CONDICIONES</b>
</p>
<p align="JUSTIFY">
1. SECRETO DE LA IDENTIFICACI&Oacute;N PERSONAL Y LA
CLAVE.-
</p>
<p align="JUSTIFY">
Es responsabilidad &uacute;nica del usuario conservar la
confidencialidad de su identificaci&oacute;n personal y su
clave para ingresar al portal, as&iacute; como de sus hijos
menores. El usuario tomara todas las medidas necesarias
para proteger el secreto y confidencialidad de la
identificaci&oacute;n personal y la clave prove&iacute;das
por el administrador del portal. La misma responsabilidad y
obligaci&oacute;n le corresponde al usuario cada vez que
solicite y obtenga un cambio o actualizaci&oacute;n de su
palabra clave. El administrador del portal no se hace
responsable de la p&eacute;rdida o extrav&iacute;o de la
identificaci&oacute;n o de la palabra clave del usuario, ni
del uso indebido y no autorizado que un tercero haga de esa
informaci&oacute;n dentro o fuera del portal.
</p>
<p align="JUSTIFY">
2. IDENTIDAD DEL USUARIO.-
</p>
<p align="JUSTIFY">
Habr&aacute; solamente una identificaci&oacute;n y palabra
clave para cada persona, y el usuario se compromete a no
solicitar m&aacute;s de una autorizaci&oacute;n por
individuo, ni solicitar o usar m&aacute;s de un nombre o
una sola identidad por persona, dentro del portal. El
usuario ingresa y navega en este portal bajo la
presunci&oacute;n de que su identificaci&oacute;n y palabra
clave corresponden a la persona que las solicit&oacute;, y
s&oacute;lo es usada y aportada en este portal por dicho
individuo, exclusivamente.
</p>
<p align="JUSTIFY">
Suplantar o sustituir la identidad del usuario o de
cualquier otra persona en este portal es un delito penado
por las leyes de Costa Rica. Ni los participantes ni el
administrador del portal ser&aacute;n responsables del uso
indebido que un tercero o terceros hagan de la
identificaci&oacute;n y/o la palabra clave del usuario. Al
recibir el usuario su identificaci&oacute;n y palabra clave
mediante comunicaci&oacute;n electr&oacute;nica o por otro
medio escrito, acepta esta responsabilidad y exonera
expresamente al administrador del portal de toda
responsabilidad, presente o futura, judicial y
extrajudicial, por el uso que el usuario u otras personas
hagan de esta informaci&oacute;n confidencial, dentro o
fuera del portal. VER EXONERACIONES.
</p>
<p align="JUSTIFY">
3. REGLAS DE USO DEL PORTAL.-
</p>
<p align="JUSTIFY">
Al solicitar su identificaci&oacute;n personal y su palabra
clave para ingresar al portal por primera vez, y cada vez
que subsecuentemente utilice dichas claves para ingresar al
portal, el usuario hace las siguientes manifestaciones y
acepta las siguientes reglas de uso del portal:
</p>
<ol type="i">
<li>
Que el usuario es mayor de edad, y con capacidad legal
para contratar, o que es menor de edad y cuenta con la
autorizaci&oacute;n respectiva de su representante o
custodio legal. Los usuarios menores de edad quedan
amparados bajo la aceptaci&oacute;n de estos
t&eacute;rminos por parte de sus padres o persona
encargada.
</li>
<li>
Que el usuario est&aacute; autorizado para usar el portal
y tener acceso a la informaci&oacute;n disponible en el
portal.
</li>
<li>
Que el usuario har&aacute; uso del portal y de la
informaci&oacute;n ofrecida en el portal para uso
personal &uacute;nicamente, y no para uso comercial.
</li>
<li>
Que el usuario no har&aacute; uso del portal ni de la
informaci&oacute;n ofrecida en el portal para
prop&oacute;sitos ilegales, o contrarios a la moral y las
buenas costumbres.
</li>
<li>
Que el usuario siempre utilizar&aacute; su verdadera
identidad al ingresar y navegar dentro del portal.
</li>
<li>
Que el usuario se abstendr&aacute; de transmitir mensajes
que sean perniciosos, difamatorios o injuriosos hacia
cualquier persona o instituci&oacute;n.
</li>
<li>
Que el usuario se abstendr&aacute; de transmitir mensajes
o ingresar informaci&oacute;n al portal que viole, sea
contrario o irrespete la Ley de Propiedad Intelectual o
la Ley de Marcas y Nombres Comerciales.
</li>
<li>
El usuario no interferir&aacute; con otros que
est&eacute;n haciendo uso de los servicios del portal al
mismo tiempo.
</li>
<li>
El usuario no transmitir&aacute; ni ingresar&aacute;
informaci&oacute;n, material, datos o archivos que
contengan virus o c&oacute;digos contaminados con virus.
</li>
<li>
El usuario no utilizar&aacute; este portal para fines
comerciales o pol&iacute;ticos ni para otros fines que no
sean los aceptados en estos t&eacute;rminos y
condiciones.
</li>
<li>
El usuario no trasmitir&aacute; mensajes que contengan
anuncios o propaganda comercial o de ning&uacute;n otro
tipo.
</li>
<li>
El usuario no transmitir&aacute; solicitudes de ayudas,
contribuciones, obras de caridad, ofrendas, o
invitaciones a participar en actividades comerciales,
pol&iacute;ticas o religiosas, cadenas, juegos,
promociones, y eventos deportivos o de cualquier otro
tipo.
</li>
</ol>
<p align="JUSTIFY">
 
</p>
<p align="JUSTIFY">
4. TERMINACI&Oacute;N DEL CONTRATO DE USO DEL PORTAL.-
</p>
<p align="JUSTIFY">
Tanto el usuario o el administrador del portal
podr&aacute;n cancelar y dar por terminado el contrato de
uso del portal en forma individual y unilateralmente, sin
contar con el consentimiento de la otra parte y sin dar
previo aviso a la otra parte, en cualquier momento, sin
responsabilidad alguna.
</p>
<p align="JUSTIFY">
 
</p>
<p align="JUSTIFY">
5. CANCELACI&Oacute;N DE LA IDENTIFICACI&Oacute;N PERSONAL
Y LA CLAVE POR USO INDEBIDO.-
</p>
<p align="JUSTIFY">
El administrador del portal se reserva el derecho de
cancelar la identificaci&oacute;n y la clave de acceso de
cualquier usuario que viole la ley o las estipulaciones de
este acuerdo, haciendo uso indebido de este portal o de la
informaci&oacute;n en &eacute;l contenida. El administrador
del portal no requerir&aacute; dar notificaci&oacute;n
previa al usuario de tal decisi&oacute;n, y el usuario
acepta exonerar completamente al administrador del portal
por las consecuencias de la cancelaci&oacute;n de la
identificaci&oacute;n y clave de acceso al portal por el
mal uso o el uso indebido o ilegal de las claves de acceso.
</p>
<p align="JUSTIFY">
6. CALIDAD DE LA INFORMACI&Oacute;N.-
</p>
<p align="JUSTIFY">
Este portal esta dise&ntilde;ado para desplegar
informaci&oacute;n ofrecida por los participantes y para
capturar informaci&oacute;n de diferentes tipos a fin de
proveer un excelente servicio que le brinde prontitud y
facilidad de acceso, y que al mismo tiempo le ahorre tiempo
y dinero, conforme a sus necesidades particulares. El
administrador del portal maneja la informaci&oacute;n con
el prop&oacute;sito de brindarle a usted un servicio
r&aacute;pido, accesible y actualizado y es un puente entre
el proveedor de la informaci&oacute;n y el receptor de la
misma. Por ende, el administrador del portal no es
responsable ni de la calidad ni de la oportunidad de la
informaci&oacute;n. En virtud de que la informaci&oacute;n
es prove&iacute;da por los participantes del portal y no
por el administrador del portal, &eacute;ste no se hace
responsable de la exactitud, veracidad o
actualizaci&oacute;n de la informaci&oacute;n disponible al
momento de ser introducida y desplegada en el portal. El
contenido de la informaci&oacute;n que usted encuentra cada
vez que ingresa a este portal no es responsabilidad del
administrador del portal y por tanto &eacute;ste no
ser&aacute; responsable por ninguna consecuencia negativa,
o por ning&uacute;n da&ntilde;o, perjuicio o lucro cesante
derivado o aparentemente derivado de estas circunstancias,
tal y como se describe en los p&aacute;rrafos siguientes.
</p>
<p align="JUSTIFY">
 
</p>
<p align="JUSTIFY">
7. CONTAMINACI&Oacute;N DE VIRUS.-
</p>
<p align="JUSTIFY">
El administrador del portal no es responsable por la
contaminaci&oacute;n electr&oacute;nica o da&ntilde;os a
computadoras, equipos de c&oacute;mputo y todos sus
accesorios, archivos, sistemas operativos y de otro tipo,
que pudieran suceder por causa de un virus o archivos
contaminados con virus o c&oacute;digos contaminados que
destruyan o perjudiquen la propiedad del usuario, ni por
problemas t&eacute;cnicos que sufra el usuario desde su
computadora o de cualquier equipo o sistema de computo al
ingresar o navegar dentro del portal.
</p>
<p align="JUSTIFY">
Es responsabilidad del usuario contar con medidas y
procesos necesarios para proteger su equipo de
c&oacute;mputo y los sistemas o software de su propiedad
contra toda posible contaminaci&oacute;n de virus y
c&oacute;digos contaminados, y de contar con procesos
activos que permitan el reemplazo o recuperaci&oacute;n de
informaci&oacute;n, datos, y procesos de c&oacute;mputo
da&ntilde;ados por un virus, conocidos como "Back-up". Es
entendido que el usuario navega en la Red Internet y en el
portal, bajo su propio riesgo.
</p>
<p align="JUSTIFY">
8. INFORMACI&Oacute;N RECIBIDA TAL Y COMO SE ENCUENTRA.-
</p>
<p align="JUSTIFY">
La informaci&oacute;n que contiene este portal se recibe en
el estado original de calidad, exactitud y veracidad en que
se encuentra y el administrador del portal no puede
garantizar, y por tanto no ofrece ning&uacute;n tipo de
garant&iacute;a de que no existen errores, alteraciones,
omisiones o modificaciones a la informaci&oacute;n que
aparece en el portal. La informaci&oacute;n desplegada en
el portal aparece tal y como fue recibida por los
mecanismos electr&oacute;nicos al ingresar al portal, de
modo que el administrador del portal no ofrece
garant&iacute;a de que el contenido de la
informaci&oacute;n sea exacto, completo o actualizado.
</p>
<p align="JUSTIFY">
9. CAMBIOS EN LA INFORMACI&Oacute;N.-
</p>
<p align="JUSTIFY">
Tanto la informaci&oacute;n como los sistemas, productos y
servicios que aparecen en este portal pueden sufrir cambios
o actualizaciones peri&oacute;dicas en cualquier momento, y
las veces que sea necesario, sin requerir previo aviso o
consentimiento del usuario. Asimismo, el administrador del
portal podr&aacute; usar la informaci&oacute;n que provea
el usuario para mejor identificar sus preferencias y
necesidades y as&iacute; dise&ntilde;ar y ofrecer un mejor
servicio que se ajuste m&aacute;s a sus predilecciones.
</p>
<p align="JUSTIFY">
10. ACCESIBILIDAD O CONECTIVIDAD AL PORTAL.-
</p>
<p align="JUSTIFY">
El acceso al portal por medio de la Red de Internet es un
mecanismo complejo, que involucra muchas partes del
sistema, <u>que son incluso sistemas o herramientas de
software producidos o manufacturados por terceros</u>,
ajenas al control directo del administrador del portal. A
pesar de que el administrador del portal maneja y opera el
portal en la Red Internet, no puede garantizar los aspectos
t&eacute;cnicos que hacen posible que el sitio en la red se
encuentre accesible a los usuarios en todo momento, o se
encuentre operando bajo cualquier circunstancia. La
conectividad a la red depende del proveedor del servicio de
Internet (ISP) y no del administrador del portal. La
conectividad a los sistemas de los participantes no
est&aacute; bajo el control del administrador del portal.
Son los aspectos t&eacute;cnicos fuera de su alcance los
que no permiten al administrador del portal garantizar el
acceso <u>irrestricto</u> del portal a toda hora. Por
tanto, el administrador del portal no garantiza que este
portal este t&eacute;cnicamente disponible a toda hora y en
todo tiempo. El administrador del portal no se hace
responsable por ning&uacute;n tipo de da&ntilde;o, presente
o futuro, sea un da&ntilde;o objetivo o subjetivo,
incidental o sustantivo, directo o indirecto o
ning&uacute;n tipo de perjuicio o lucro cesante, presente o
futuro causado al usuario o a terceros por falta de
conexi&oacute;n o de acceso al portal y/o a la Red
Internet, o por atrasos y demoras, incluyendo conexiones
parciales, defectuosas, interrumpidas o intermitentes.
</p>
<p align="JUSTIFY">
11. DERECHOS DE MARCA Y OTROS PROTEGIDOS.-
</p>
<p align="JUSTIFY">
Excepto por la informaci&oacute;n proveniente directamente
del o los participantes, el contenido total de este
servicio y el concepto de este portal, incluyendo, pero no
limitado al dise&ntilde;o, colores, marcas, nombres
comerciales, im&aacute;genes y sonidos, son propiedad del
administrador del portal, y se encuentran protegidos por la
Ley de Propiedad Intelectual y la Ley de Marcas y Nombres
Comerciales.
</p>
<p align="JUSTIFY">
12. NEXOS A OTROS SITIOS DE LA RED INTERNET.-
</p>
<p align="JUSTIFY">
Conforme a nuestro prop&oacute;sito de proveer un excelente
servicio, este portal podr&aacute; ofrecer conexiones a
otros sitios de la Red que son de terceros y que tienen sus
propios t&eacute;rminos y condiciones. El administrador del
portal no es responsable por el contenido de estos sitios,
y es entendido que dichas conexiones se ofrecen como un
servicio para conveniencia del usuario. Por tanto, el
usuario acepta ingresar a estos sitios cuando navegue por
el portal o la Red Internet bajo su propio riesgo y bajo
los t&eacute;rminos y condiciones fijados por dichos
sitios, y no por los t&eacute;rminos y condiciones de este
portal.
</p>
<p align="JUSTIFY">
13. MODIFICACIONES A LOS TERMINOS Y CONDICIONES DE USO.- El
administrador del portal se reserva el derecho de efectuar
cambios y hacer modificaciones a los t&eacute;rminos y
condiciones de uso de este portal, sin previo aviso o
consentimiento del usuario. El usuario deber&aacute;
revisar estos t&eacute;rminos y condiciones
peri&oacute;dicamente para quedar enterado y adherirse al
nuevo contenido cada vez que ocurra una
actualizaci&oacute;n.
</p>
<p align="JUSTIFY">
14. JURISDICCI&Oacute;N.-
</p>
<p align="JUSTIFY">
El usuario acepta y est&aacute; de acuerdo que los derechos
y obligaciones derivadas del uso y operaci&oacute;n de este
portal y todo servicio derivado del mismo, se
regir&aacute;n por las leyes de la Rep&uacute;blica de
Costa Rica y queda sometido a la jurisdicci&oacute;n de los
Tribunales de San Jos&eacute;, Costa Rica.
</p>
<p align="JUSTIFY">
15. SEGURIDAD EN LA TRANSMISI&Oacute;N DE
<u>INFORMACI&Oacute;N Y</u> DATOS.
</p>
<p align="JUSTIFY">
Es entendido que para operar el portal se requieren otros
sistemas y herramientas de software no producidos por el
administrador del portal. El usuario acepta el uso de esos
sistemas y herramientas de software manufacturados y
producidos por terceros, incluyendo pero no limitado a
herramientas de b&uacute;squeda y exploraci&oacute;n, o
"browsers" que dan soporte al protocolo de seguridad propio
del administrador del portal o que son compatibles con el
protocolo usado por &eacute;ste. El usuario est&aacute; de
acuerdo que se adopten sistemas y herramientas de software
que brinden soporte al protocolo de engranaje gradual de
seguridad, conocido como Secure Socket Layer (SSL) y otros
protocolos seleccionados por el administrador del portal,
as&iacute; como a respetar y utilizar los protocolos de
acceso y de servicio adoptados por el administrador del
portal para dar soporte a dichos protocolos. El usuario
accede a que se adopten estos sistemas y herramientas de
software que han sido manufacturados por terceros. Es
entendido que el administrador del portal no es responsable
por la capacidad, eficiencia, duraci&oacute;n, rendimiento,
infalibilidad, defectos, interrupciones y fallas de estos
sistemas y herramientas de software. El administrador del
portal tampoco est&aacute; obligado a notificar al usuario,
ni notificar&aacute; al usuario de ning&uacute;n ajuste,
sustituci&oacute;n, actualizaci&oacute;n (upgrade) o mejora
que realice en dichos sistemas o herramientas de software.
El administrador del portal tampoco es responsable por la
p&eacute;rdida de informaci&oacute;n o de datos durante su
transmisi&oacute;n electr&oacute;nica a trav&eacute;s del
portal o de cualquier red de c&oacute;mputo o instalaciones
de telecomunicaci&oacute;n, incluyendo pero no limitado a,
la red Internet.
</p>
<p>
<u>16. ACEPTACI&Oacute;N DE RIESGO AL USAR LA RED
INTERNET.-</u>
</p>
<p align="JUSTIFY">
El usuario reconoce y acepta la posibilidad y el riesgo
inherente de que en cualquier momento la
comunicaci&oacute;n electr&oacute;nica existente en el
portal puede quedar expuesta a terceros no autorizados a
trav&eacute;s de la red Internet, otras instalaciones de la
red, <u>otros mecanismos de telecomunicaciones</u> o por
cualquier otro medio electr&oacute;nico.
</p>
<p align="JUSTIFY">
17. SEGURIDAD EN EL ALMACENAMIENTO DE LOS DATOS
</p>
<p align="JUSTIFY">
El administrador del portal mantendr&aacute; la seguridad
de la informaci&oacute;n y la seguridad de los datos dentro
del portal, mediante el uso de protocolos de
<u>protecci&oacute;n y</u> seguridad, y el m&eacute;todo de
encriptamiento, as&iacute; como de cualquier otro medio que
&eacute;ste escoja o que sugiera y/o requiera que el
usuario utilice. No obstante, el administrador del portal
no es responsable por la p&eacute;rdida, borrado o falla en
la transmisi&oacute;n o almacenamiento de la
informaci&oacute;n o datos suministrados por el usuario o
por terceros al portal, ni por la falta de efectividad,
fallas, impurezas o debilidades en los protocolos de
seguridad, el m&eacute;todo de encriptamiento, las claves
de acceso, c&oacute;digos u otros sistemas de seguridad
empleados por &eacute;ste.
</p>
<p align="JUSTIFY">
<font color="#ff0000"> </font>
</p>

<p align="CENTER">
<b> </b>
</p>
<p align="CENTER">
<b>EXONERACIONES DE RESPONSABILIDAD Y RENUNCIAS.-</b>
</p>
<p align="JUSTIFY">
I.- Cuando el usuario solicita su palabra clave y su
identificaci&oacute;n personalizada para ingresar al portal
por primera vez, y cada vez que subsecuentemente utilice
dichas claves para ingresar al portal, &eacute;ste hace las
siguientes renuncias y en el acto exonera totalmente al
administrador del portal por cualquier da&ntilde;o,
presente o futuro, sea un da&ntilde;o objetivo o subjetivo,
incidental o sustantivo, directo o indirecto, o por
cualquier tipo de perjuicio, o lucro cesante presente o
futuro, ocasionado o aparentemente ocasionado al usuario o
a terceros por la falta de exactitud, precisi&oacute;n,
veracidad, omisiones o baja calidad de la
informaci&oacute;n ofrecida o desplegada en el portal. El
usuario tambi&eacute;n exonera al administrador del portal
por informaci&oacute;n incompleta o que no se visualice en
su totalidad en el portal.
</p>
<p align="JUSTIFY">
II.- El usuario exonera al administrador del portal de toda
responsabilidad presente o futura y renuncia a cualquier
reclamo y a toda acci&oacute;n judicial o extrajudicial,
sea civil, penal, administrativa, fiscal, laboral o de
cualquier otro tipo, por p&eacute;rdidas, da&ntilde;os,
perjuicios o lucro cesante, derivados o supuestamente
derivados de:
</p>
<ul>
<li>
<u>El</u> uso indebido que el mismo usuario o terceros
hagan de su palabra clave e identificaci&oacute;n de
acceso, dentro o fuera de este portal.
</li>
</ul>
<ul>
<li>
La inhabilidad del usuario de conectarse a la Red
Internet o al portal, o de ingresar al portal. Esta
exoneraci&oacute;n se aplica incluso cuando el acceso al
portal no sea posible por conexiones defectuosas, de baja
calidad, incompletas, intermitentes o interrumpidas.
</li>
</ul>
<ul>
<li>
de que en cualquier momento la comunicaci&oacute;n
electr&oacute;nica existente en el portal quede expuesta
a terceros no autorizados.
</li>
</ul>
<ul>
<li>
De cualquier problema t&eacute;cnico, perdida o
da&ntilde;o a la propiedad que sufra el usuario en su
computadora, incluyendo efectos de virus o c&oacute;digos
contaminados con virus y otros mecanismos da&ntilde;inos,
en cualquier computadora o equipo, incluso equipo
accesorio y en cualquier sistema operativo, al intentar
ingresar o al usar este portal.
</li>
</ul>
<ul>
<li>
La p&eacute;rdida, borrado o falla en la
transmisi&oacute;n o almacenamiento de la
informaci&oacute;n o datos suministrados por el usuario o
por terceros al portal, ni por la falta de efectividad,
fallas, impurezas o debilidades en los protocolos de
protecci&oacute;n y seguridad, el m&eacute;todo de
encriptamiento, la identificaci&oacute;n personal y las
claves de acceso, c&oacute;digos u otros sistemas de
seguridad empleados por el administrador del portal.
</li>
</ul>
<ul>
<li>
Los defectos, interrupciones, fallas, atrasos,
inconveniencias, p&eacute;rdidas o da&ntilde;os sufridos
o derivados del uso de sistemas y herramientas de
software manufacturados y producidos por terceros o de
los sistemas de control, protecci&oacute;n y seguridad.
</li>
</ul>
<p align="JUSTIFY">
III.- Es entendido que esta renuncia es expresa, abarca
todos los supuestos anteriores y no es una renuncia
t&aacute;cita, sino que queda expresamente manifiesta en el
momento que el usuario solicita y recibe por primera vez su
identificaci&oacute;n y su palabra clave para ingresar al
portal, y cada vez que subsecuentemente ingrese al portal
utilizando dicha identificaci&oacute;n personalizada y su
palabra clave.
</p>
