<?xml version="1.0" encoding="UTF-8" ?> 
- <wsdl:definitions targetNamespace="http://webservice.Basura.sif" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://webservice.Basura.sif" xmlns:intf="http://webservice.Basura.sif" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns1="http://rpc.xml.coldfusion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
- <!-- WSDL created by Macromedia ColdFusion MX version 7,0,0,91690
  --> 
- <wsdl:types>
- <schema targetNamespace="http://webservice.Basura.sif" xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://rpc.xml.coldfusion" /> 
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/" /> 
- <complexType name="ArrayOf_xsd_string">
- <complexContent>
- <restriction base="soapenc:Array">
  <attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:string[]" /> 
  </restriction>
  </complexContent>
  </complexType>
- <complexType name="ArrayOfArrayOf_xsd_anyType">
- <complexContent>
- <restriction base="soapenc:Array">
  <attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:anyType[][]" /> 
  </restriction>
  </complexContent>
  </complexType>
  </schema>
- <schema targetNamespace="http://rpc.xml.coldfusion" xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://webservice.Basura.sif" /> 
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/" /> 
- <complexType name="QueryBean">
- <sequence>
  <element name="columnList" nillable="true" type="impl:ArrayOf_xsd_string" /> 
  <element name="data" nillable="true" type="impl:ArrayOfArrayOf_xsd_anyType" /> 
  </sequence>
  </complexType>
- <complexType name="CFCInvocationException">
  <sequence /> 
  </complexType>
  </schema>
  </wsdl:types>
  <wsdl:message name="pruebaRequest" /> 
- <wsdl:message name="pruebaResponse">
  <wsdl:part name="pruebaReturn" type="xsd:double" /> 
  </wsdl:message>
- <wsdl:message name="listaEmpresasResponse">
  <wsdl:part name="listaEmpresasReturn" type="tns1:QueryBean" /> 
  </wsdl:message>
  <wsdl:message name="listaEmpresasRequest" /> 
- <wsdl:message name="CFCInvocationException">
  <wsdl:part name="fault" type="tns1:CFCInvocationException" /> 
  </wsdl:message>
- <wsdl:portType name="wsCheck">
- <wsdl:operation name="listaEmpresas">
  <wsdl:input message="impl:listaEmpresasRequest" name="listaEmpresasRequest" /> 
  <wsdl:output message="impl:listaEmpresasResponse" name="listaEmpresasResponse" /> 
  <wsdl:fault message="impl:CFCInvocationException" name="CFCInvocationException" /> 
  </wsdl:operation>
- <wsdl:operation name="prueba">
  <wsdl:input message="impl:pruebaRequest" name="pruebaRequest" /> 
  <wsdl:output message="impl:pruebaResponse" name="pruebaResponse" /> 
  <wsdl:fault message="impl:CFCInvocationException" name="CFCInvocationException" /> 
  </wsdl:operation>
  </wsdl:portType>
- <wsdl:binding name="wsCheck.cfcSoapBinding" type="impl:wsCheck">
  <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" /> 
- <wsdl:operation name="listaEmpresas">
  <wsdlsoap:operation soapAction="" /> 
- <wsdl:input name="listaEmpresasRequest">
  <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://webservice.Basura.sif" use="encoded" /> 
  </wsdl:input>
- <wsdl:output name="listaEmpresasResponse">
  <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://webservice.Basura.sif" use="encoded" /> 
  </wsdl:output>
- <wsdl:fault name="CFCInvocationException">
  <wsdlsoap:fault encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" name="CFCInvocationException" namespace="http://webservice.Basura.sif" use="encoded" /> 
  </wsdl:fault>
  </wsdl:operation>
- <wsdl:operation name="prueba">
  <wsdlsoap:operation soapAction="" /> 
- <wsdl:input name="pruebaRequest">
  <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://webservice.Basura.sif" use="encoded" /> 
  </wsdl:input>
- <wsdl:output name="pruebaResponse">
  <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://webservice.Basura.sif" use="encoded" /> 
  </wsdl:output>
- <wsdl:fault name="CFCInvocationException">
  <wsdlsoap:fault encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" name="CFCInvocationException" namespace="http://webservice.Basura.sif" use="encoded" /> 
  </wsdl:fault>
  </wsdl:operation>
  </wsdl:binding>
- <wsdl:service name="wsCheckService">
- <wsdl:port binding="impl:wsCheck.cfcSoapBinding" name="wsCheck.cfc">
  <wsdlsoap:address location="http://localhost:8080/cfmx/sif/Basura/webservice/wsCheck.cfc" /> 
  </wsdl:port>
  </wsdl:service>
  </wsdl:definitions>