/*
 * Generated by JasperReports - 06/07/04 04:13 PM
 */
import dori.jasper.engine.*;
import dori.jasper.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class depreciacionMes extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_Ecodigo = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_Mes = null;
    private JRFillParameter parameter_Centro = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_Periodo = null;
    private JRFillParameter parameter_Categoria = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_nombMes = null;
    private JRFillParameter parameter_Clase = null;

    private JRFillField field_Edescripcion = null;
    private JRFillField field_ACcodigodesc = null;
    private JRFillField field_CFdescripcion = null;
    private JRFillField field_ACdescripcion = null;
    private JRFillField field_categoria = null;
    private JRFillField field_AFSvalrev = null;
    private JRFillField field_clasedescripcion = null;
    private JRFillField field_CFid = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_totclasevalrev = null;
    private JRFillVariable variable_totcatvalrev = null;
    private JRFillVariable variable_totcfvalrev = null;
    private JRFillVariable variable_totGenvalrev = null;
    private JRFillVariable variable_Categoria_COUNT = null;
    private JRFillVariable variable_Clase_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_Ecodigo = (JRFillParameter)parsm.get("Ecodigo");
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_Mes = (JRFillParameter)parsm.get("Mes");
        parameter_Centro = (JRFillParameter)parsm.get("Centro");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_Periodo = (JRFillParameter)parsm.get("Periodo");
        parameter_Categoria = (JRFillParameter)parsm.get("Categoria");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");
        parameter_nombMes = (JRFillParameter)parsm.get("nombMes");
        parameter_Clase = (JRFillParameter)parsm.get("Clase");

        field_Edescripcion = (JRFillField)fldsm.get("Edescripcion");
        field_ACcodigodesc = (JRFillField)fldsm.get("ACcodigodesc");
        field_CFdescripcion = (JRFillField)fldsm.get("CFdescripcion");
        field_ACdescripcion = (JRFillField)fldsm.get("ACdescripcion");
        field_categoria = (JRFillField)fldsm.get("categoria");
        field_AFSvalrev = (JRFillField)fldsm.get("AFSvalrev");
        field_clasedescripcion = (JRFillField)fldsm.get("clasedescripcion");
        field_CFid = (JRFillField)fldsm.get("CFid");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_totclasevalrev = (JRFillVariable)varsm.get("totclasevalrev");
        variable_totcatvalrev = (JRFillVariable)varsm.get("totcatvalrev");
        variable_totcfvalrev = (JRFillVariable)varsm.get("totcfvalrev");
        variable_totGenvalrev = (JRFillVariable)varsm.get("totGenvalrev");
        variable_Categoria_COUNT = (JRFillVariable)varsm.get("Categoria_COUNT");
        variable_Clase_COUNT = (JRFillVariable)varsm.get("Clase_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 307 : // printWhen_31
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 276 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 268 : // variable_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 250 : // variable_totclasevalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 303 : // printWhen_29
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 254 : // group_Categoria
            {
                value = (java.lang.Object)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 293 : // printWhen_23
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 273 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_clasedescripcion.getValue()));
                break;
            }
            case 246 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 248 : // parameterDefaultValue_Categoria
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 261 : // textField_3
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatvalrev.getValue()));
                break;
            }
            case 283 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 298 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)parameter_nombMes.getValue()));
                break;
            }
            case 264 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getValue()));
                break;
            }
            case 253 : // variable_totGenvalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 267 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 309 : // printWhen_32
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 247 : // parameterDefaultValue_Centro
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 265 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 285 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 288 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) == null));
                break;
            }
            case 312 : // printWhen_34
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 258 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 249 : // parameterDefaultValue_Clase
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 294 : // printWhen_24
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 311 : // printWhen_33
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 278 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 282 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_clasedescripcion.getValue()));
                break;
            }
            case 310 : // textField_19
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 291 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 256 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 245 : // parameterDefaultValue_Mes
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(03));
                break;
            }
            case 244 : // parameterDefaultValue_Periodo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(2002));
                break;
            }
            case 295 : // printWhen_25
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 238 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 236 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 262 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 300 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)field_CFid.getValue()));
                break;
            }
            case 302 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 308 : // textField_18
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " de ");
                break;
            }
            case 289 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 274 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 305 : // printWhen_30
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 239 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 306 : // textField_17
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 292 : // printWhen_22
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 299 : // printWhen_27
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 313 : // textField_20
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGenvalrev.getValue()));
                break;
            }
            case 284 : // textField_10
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totclasevalrev.getValue()));
                break;
            }
            case 257 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getValue()));
                break;
            }
            case 277 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 297 : // printWhen_26
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 259 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 269 : // variableInitialValue_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 275 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_ACcodigodesc.getValue()));
                break;
            }
            case 304 : // textField_16
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 251 : // variable_totcatvalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 280 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 279 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_ACcodigodesc.getValue()));
                break;
            }
            case 263 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 270 : // group_Clase
            {
                value = (java.lang.Object)(((java.lang.String)field_clasedescripcion.getValue()));
                break;
            }
            case 290 : // printWhen_21
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 301 : // printWhen_28
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 241 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 272 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 243 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 242 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 271 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 255 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 296 : // textField_12
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_Periodo.getValue()));
                break;
            }
            case 287 : // variableInitialValue_Clase_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 260 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 237 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 286 : // variable_Clase_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 266 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 281 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 252 : // variable_totcfvalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 240 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 307 : // printWhen_31
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 276 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 268 : // variable_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 250 : // variable_totclasevalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getOldValue()));
                break;
            }
            case 303 : // printWhen_29
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 254 : // group_Categoria
            {
                value = (java.lang.Object)(((java.lang.String)field_ACdescripcion.getOldValue()));
                break;
            }
            case 293 : // printWhen_23
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 273 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_clasedescripcion.getOldValue()));
                break;
            }
            case 246 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 248 : // parameterDefaultValue_Categoria
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 261 : // textField_3
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatvalrev.getOldValue()));
                break;
            }
            case 283 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 298 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)parameter_nombMes.getValue()));
                break;
            }
            case 264 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getOldValue()));
                break;
            }
            case 253 : // variable_totGenvalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getOldValue()));
                break;
            }
            case 267 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getOldValue()));
                break;
            }
            case 309 : // printWhen_32
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 247 : // parameterDefaultValue_Centro
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 265 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 285 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 288 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) == null));
                break;
            }
            case 312 : // printWhen_34
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 258 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 249 : // parameterDefaultValue_Clase
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 294 : // printWhen_24
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 311 : // printWhen_33
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 278 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 282 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_clasedescripcion.getOldValue()));
                break;
            }
            case 310 : // textField_19
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 291 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getOldValue()));
                break;
            }
            case 256 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 245 : // parameterDefaultValue_Mes
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(03));
                break;
            }
            case 244 : // parameterDefaultValue_Periodo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(2002));
                break;
            }
            case 295 : // printWhen_25
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 238 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 236 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 262 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 300 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)field_CFid.getOldValue()));
                break;
            }
            case 302 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getOldValue()));
                break;
            }
            case 308 : // textField_18
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " de ");
                break;
            }
            case 289 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 274 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 305 : // printWhen_30
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 239 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 306 : // textField_17
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 292 : // printWhen_22
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 299 : // printWhen_27
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 313 : // textField_20
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGenvalrev.getOldValue()));
                break;
            }
            case 284 : // textField_10
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totclasevalrev.getOldValue()));
                break;
            }
            case 257 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getOldValue()));
                break;
            }
            case 277 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 297 : // printWhen_26
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 259 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getOldValue()));
                break;
            }
            case 269 : // variableInitialValue_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 275 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_ACcodigodesc.getOldValue()));
                break;
            }
            case 304 : // textField_16
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getOldValue()));
                break;
            }
            case 251 : // variable_totcatvalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getOldValue()));
                break;
            }
            case 280 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 279 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_ACcodigodesc.getOldValue()));
                break;
            }
            case 263 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 270 : // group_Clase
            {
                value = (java.lang.Object)(((java.lang.String)field_clasedescripcion.getOldValue()));
                break;
            }
            case 290 : // printWhen_21
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 301 : // printWhen_28
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 241 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 272 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 243 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 242 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 271 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 255 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 296 : // textField_12
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_Periodo.getValue()));
                break;
            }
            case 287 : // variableInitialValue_Clase_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 260 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 237 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 286 : // variable_Clase_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 266 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 281 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 252 : // variable_totcfvalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getOldValue()));
                break;
            }
            case 240 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 307 : // printWhen_31
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 276 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 268 : // variable_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 250 : // variable_totclasevalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 303 : // printWhen_29
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 254 : // group_Categoria
            {
                value = (java.lang.Object)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 293 : // printWhen_23
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 273 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_clasedescripcion.getValue()));
                break;
            }
            case 246 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 248 : // parameterDefaultValue_Categoria
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 261 : // textField_3
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatvalrev.getEstimatedValue()));
                break;
            }
            case 283 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 298 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)parameter_nombMes.getValue()));
                break;
            }
            case 264 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getValue()));
                break;
            }
            case 253 : // variable_totGenvalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 267 : // textField_5
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 309 : // printWhen_32
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 247 : // parameterDefaultValue_Centro
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 265 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 285 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 288 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) == null));
                break;
            }
            case 312 : // printWhen_34
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 258 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 249 : // parameterDefaultValue_Clase
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 294 : // printWhen_24
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 311 : // printWhen_33
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 278 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 282 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_clasedescripcion.getValue()));
                break;
            }
            case 310 : // textField_19
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 291 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 256 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 245 : // parameterDefaultValue_Mes
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(03));
                break;
            }
            case 244 : // parameterDefaultValue_Periodo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(2002));
                break;
            }
            case 295 : // printWhen_25
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 238 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 236 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 262 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 300 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)field_CFid.getValue()));
                break;
            }
            case 302 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 308 : // textField_18
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " de ");
                break;
            }
            case 289 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 274 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 305 : // printWhen_30
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 239 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 306 : // textField_17
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 292 : // printWhen_22
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 299 : // printWhen_27
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 313 : // textField_20
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGenvalrev.getEstimatedValue()));
                break;
            }
            case 284 : // textField_10
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totclasevalrev.getEstimatedValue()));
                break;
            }
            case 257 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getValue()));
                break;
            }
            case 277 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 297 : // printWhen_26
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 259 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 269 : // variableInitialValue_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 275 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_ACcodigodesc.getValue()));
                break;
            }
            case 304 : // textField_16
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 251 : // variable_totcatvalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 280 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 279 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_ACcodigodesc.getValue()));
                break;
            }
            case 263 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 270 : // group_Clase
            {
                value = (java.lang.Object)(((java.lang.String)field_clasedescripcion.getValue()));
                break;
            }
            case 290 : // printWhen_21
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 301 : // printWhen_28
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 241 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 272 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 243 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 242 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 271 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 255 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 296 : // textField_12
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_Periodo.getValue()));
                break;
            }
            case 287 : // variableInitialValue_Clase_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 260 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 237 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 286 : // variable_Clase_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 266 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 281 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 252 : // variable_totcfvalrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSvalrev.getValue()));
                break;
            }
            case 240 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
