/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */
package com.soin.rh.calculo;

public interface CalculatorConstants {

  int EOF = 0;
  int IDENTIFIER = 4;
  int NUMBER = 5;
  int DIGIT = 6;
  int LETTER = 7;
  int EOL = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<DIGIT>",
    "<LETTER>",
    "\"\\n\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
