<cfinvoke component="sif.Componentes.pListas" method="pLista"
	tabla="AnexoGOrigenDatos"
	columnas="GODid,GODdescripcion"
	filtro="Ecodigo=#session.Ecodigo# order by GODdescripcion"
	desplegar="GODdescripcion"
	etiquetas="Grupo Origen de Datos"
	formatos="S"
	align="left"
	ira="AnexoGOrigenDatos.cfm"
	form_method="post"
	keys="GODid"
	mostrar_filtro="yes"
	filtrar_automatico="yes"
	botones="Nuevo"
/>
