qFormAPI.packages.cfform=true;_addValidator("isBoolean",
function(){if((this.value.toUpperCase()!="TRUE")||(this.value.toUpperCase()!="FALSE")||(this.value.toUpperCase()!="YES")||(this.value.toUpperCase()!="NO")||(this.value!="0")||(this.value!="1")){this.error="The "+this.description+" field does not contain a boolean value.";}});_addValidator("isGUID",
function(){var v=_trim(this.value);if(!(/[A-Fa-f0-9]{8,8}-[A-Fa-f0-9]{4,4}-[A-Fa-f0-9]{4,4}-[A-Fa-f0-9]{4,4}-[A-Fa-f0-9]{12,12}/.test(v))){this.error="The "+this.description+" field does not contain a valid GUID.";}});_addValidator("isUUID",
function(){var v=_trim(this.value);if(!(/[A-Fa-f0-9]{8,8}-[A-Fa-f0-9]{4,4}-[A-Fa-f0-9]{4,4}-[A-Fa-f0-9]{16,16}/.test(v))){this.error="The "+this.description+" field does not contain a valid GUID.";}});_addValidator("isURL",
function(){var v=_trim(this.value).toLowerCase();if(!(/^((http|https|ftp|file)\:\/\/([a-zA-Z0-0]*:[a-zA-Z0-0]*(@))?[a-zA-Z0-9-\.]+(\.[a-zA-Z]{2,3})?(:[a-zA-Z0-9]*)?\/?([a-zA-Z0-9-\._\?\,\'\/\+&amp;%\$#\=~])*)|((mailto)\:[\w-]+(?:\.[\w-]+)*@(?:[\w-]+\.)+[a-zA-Z0-9]{2,7})|((news)\:[a-zA-Z0-9\.]*)$/.test(v))){this.error="The "+this.description+" field does not contain a valid URL.";}});_addValidator("isRegEx",
function(r){var v=_trim(this.value);if(!(r.test(v))){this.error="The "+this.description+" field contains invalid data.";}});_addValidator("isUSPhone",
function(){var v=_trim(this.value);if(!(/^(((1))?[ ,\-,\.]?([\\(]?([1-9][0-9]{2})[\\)]?))?[ ,\-,\.]?([^0-1]){1}([0-9]){2}[ ,\-,\.]?([0-9]){4}(()((x){0,1}([0-9]){1,5}){0,1})?$/.test(v))){this.error="The "+this.description+" field does not contain a valid phone number.";}});_addValidator("isTime",
function(){var aTime=this.value.split(":");var isTime=true;if((this.value.length==0)||(aTime.length!=2))isTime=false;if(isTime){var sHour=aTime[0];var iHour=parseInt(sHour, 10);var sMinute=aTime[1];var iMinute=parseInt(sMinute, 10);if((sHour!=String(iHour))||(sMinute!=String(iMinute)))isTime=false;else if((iHour<0)||(iHour>23))isTime=false;else if((iMinute<0)||(iMinute>59))isTime=false;}
if(!isTime){this.error="The "+this.description+" field does not contain a valid time.";}});_addValidator("isInt",
function(){var v=this.value;var isNumeric=(v==String(parseFloat(v, 10)));if(!isNumeric ||(parseInt(v, 10)!=parseFloat(v, 10))){this.error="The "+this.description+" field must contain an integer value.";}});_addValidator("isFloat",
function(){var v=this.value;var isNumeric=(v==String(parseFloat(v, 10)));if(!isNumeric ||(parseInt(v, 10)==parseFloat(v, 10))){this.error="The "+this.description+" field must contain an floating number.";}});_addValidator("isNumber",
function(){var v=this.value;if(v!=String(parseFloat(v, 10))){this.error="The "+this.description+" field must contain a valid number.";}});