<html>
    <title>Paleta</title>
    <body>
        <form name="colorform">
            <MAP NAME="FrontPageMap0">
                <AREA SHAPE="RECT" COORDS="1, 1, 7, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00FF00');window.close()">
                <AREA SHAPE="RECT" COORDS="9, 1, 15, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00FF33');window.close()">
                <AREA SHAPE="RECT" COORDS="17, 1, 23, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00FF66');window.close()">
                <AREA SHAPE="RECT" COORDS="25, 1, 31, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00FF99');window.close()">
                <AREA SHAPE="RECT" COORDS="33, 1, 39, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00FFCC');window.close()">
                <AREA SHAPE="RECT" COORDS="41, 1, 47, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00FFFF');window.close()">
                <AREA SHAPE="RECT" COORDS="49, 1, 55, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33FF00');window.close()">
                <AREA SHAPE="RECT" COORDS="57, 1, 63, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33FF33');window.close()">
                <AREA SHAPE="RECT" COORDS="65, 1, 71, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33FF66');window.close()">
                <AREA SHAPE="RECT" COORDS="73, 1, 79, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33FF99');window.close()">
                <AREA SHAPE="RECT" COORDS="81, 1, 87, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33FFCC');window.close()">
                <AREA SHAPE="RECT" COORDS="89, 1, 95, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33FFFF');window.close()">
                <AREA SHAPE="RECT" COORDS="97, 1, 103, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66FF00');window.close()">
                <AREA SHAPE="RECT" COORDS="105, 1, 111, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66FF33');window.close()">
                <AREA SHAPE="RECT" COORDS="113, 1, 119, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66FF66');window.close()">
                <AREA SHAPE="RECT" COORDS="121, 1, 127, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66FF99');window.close()">
                <AREA SHAPE="RECT" COORDS="129, 1, 135, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66FFCC');window.close()">
                <AREA SHAPE="RECT" COORDS="137, 1, 143, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66FFFF');window.close()">
                <AREA SHAPE="RECT" COORDS="145, 1, 151, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99FF00');window.close()">
                <AREA SHAPE="RECT" COORDS="153, 1, 159, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99FF33');window.close()">
                <AREA SHAPE="RECT" COORDS="161, 1, 167, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99FF66');window.close()">
                <AREA SHAPE="RECT" COORDS="169, 1, 175, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99FF99');window.close()">
                <AREA SHAPE="RECT" COORDS="177, 1, 183, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99FFCC');window.close()">
                <AREA SHAPE="RECT" COORDS="185, 1, 191, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99FFFF');window.close()">
                <AREA SHAPE="RECT" COORDS="193, 1, 199, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCFF00');window.close()">
                <AREA SHAPE="RECT" COORDS="201, 1, 207, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCFF33');window.close()">
                <AREA SHAPE="RECT" COORDS="209, 1, 215, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCFF66');window.close()">
                <AREA SHAPE="RECT" COORDS="217, 1, 223, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCFF99');window.close()">
                <AREA SHAPE="RECT" COORDS="225, 1, 231, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCFFCC');window.close()">
                <AREA SHAPE="RECT" COORDS="233, 1, 239, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCFFFF');window.close()">
                <AREA SHAPE="RECT" COORDS="241, 1, 247, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFFF00');window.close()">
                <AREA SHAPE="RECT" COORDS="249, 1, 255, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFFF33');window.close()">
                <AREA SHAPE="RECT" COORDS="257, 1, 263, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFFF66');window.close()">
                <AREA SHAPE="RECT" COORDS="265, 1, 271, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFFF99');window.close()">
                <AREA SHAPE="RECT" COORDS="273, 1, 279, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFFFCC');window.close()">
                <AREA SHAPE="RECT" COORDS="281, 1, 287, 10" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFFFFF');window.close()">
                <AREA SHAPE="RECT" COORDS="1, 12, 7, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00CC00');window.close()">
                <AREA SHAPE="RECT" COORDS="9, 12, 15, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00CC33');window.close()">
                <AREA SHAPE="RECT" COORDS="17, 12, 23, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00CC66');window.close()">
                <AREA SHAPE="RECT" COORDS="25, 12, 31, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00CC99');window.close()">
                <AREA SHAPE="RECT" COORDS="33, 12, 39, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00CCCC');window.close()">
                <AREA SHAPE="RECT" COORDS="41, 12, 47, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '00CCFF');window.close()">
                <AREA SHAPE="RECT" COORDS="49, 12, 55, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33CC00');window.close()">
                <AREA SHAPE="RECT" COORDS="57, 12, 63, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33CC33');window.close()">
                <AREA SHAPE="RECT" COORDS="65, 12, 71, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33CC66');window.close()">
                <AREA SHAPE="RECT" COORDS="73, 12, 79, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33CC99');window.close()">
                <AREA SHAPE="RECT" COORDS="81, 12, 87, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33CCCC');window.close()">
                <AREA SHAPE="RECT" COORDS="89, 12, 95, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '33CCFF');window.close()">
                <AREA SHAPE="RECT" COORDS="97, 12, 103, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66CC00');window.close()">
                <AREA SHAPE="RECT" COORDS="105, 12, 111, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66CC33');window.close()">
                <AREA SHAPE="RECT" COORDS="113, 12, 119, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66CC66');window.close()">
                <AREA SHAPE="RECT" COORDS="121, 12, 127, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66CC99');window.close()">
                <AREA SHAPE="RECT" COORDS="129, 12, 135, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66CCCC');window.close()">
                <AREA SHAPE="RECT" COORDS="137, 12, 143, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '66CCFF');window.close()">
                <AREA SHAPE="RECT" COORDS="145, 12, 151, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99CC00');window.close()">
                <AREA SHAPE="RECT" COORDS="153, 12, 159, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99CC33');window.close()">
                <AREA SHAPE="RECT" COORDS="161, 12, 167, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99CC66');window.close()">
                <AREA SHAPE="RECT" COORDS="169, 12, 175, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99CC99');window.close()">
                <AREA SHAPE="RECT" COORDS="177, 12, 183, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99CCCC');window.close()">
                <AREA SHAPE="RECT" COORDS="185, 12, 191, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '99CCFF');window.close()">
                <AREA SHAPE="RECT" COORDS="193, 12, 199, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCCC00');window.close()">
                <AREA SHAPE="RECT" COORDS="201, 12, 207, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCCC33');window.close()">
                <AREA SHAPE="RECT" COORDS="209, 12, 215, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCCC66');window.close()">
                <AREA SHAPE="RECT" COORDS="217, 12, 223, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCCC99');window.close()">
                <AREA SHAPE="RECT" COORDS="225, 12, 231, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCCCCC');window.close()">
                <AREA SHAPE="RECT" COORDS="233, 12, 239, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CCCCFF');window.close()">
                <AREA SHAPE="RECT" COORDS="241, 12, 247, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFCC00');window.close()">
                <AREA SHAPE="RECT" COORDS="249, 12, 255, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFCC33');window.close()">
                <AREA SHAPE="RECT" COORDS="257, 12, 263, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFCC66');window.close()">
                <AREA SHAPE="RECT" COORDS="265, 12, 271, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFCC99');window.close()">
                <AREA SHAPE="RECT" COORDS="273, 12, 279, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFCCCC');window.close()">
                <AREA SHAPE="RECT" COORDS="281, 12, 287, 21" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FFCCFF');window.close()">
                <AREA SHAPE="RECT" COORDS="1, 23, 7, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '009900');window.close()">
                <AREA SHAPE="RECT" COORDS="9, 23, 15, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '009933');window.close()">
                <AREA SHAPE="RECT" COORDS="17, 23, 23, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '009966');window.close()">
                <AREA SHAPE="RECT" COORDS="25, 23, 31, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '009999');window.close()">
                <AREA SHAPE="RECT" COORDS="33, 23, 39, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '0099CC');window.close()">
                <AREA SHAPE="RECT" COORDS="41, 23, 47, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '0099FF');window.close()">
                <AREA SHAPE="RECT" COORDS="49, 23, 55, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '339900');window.close()">
                <AREA SHAPE="RECT" COORDS="57, 23, 63, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '339933');window.close()">
                <AREA SHAPE="RECT" COORDS="65, 23, 71, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '339966');window.close()">
                <AREA SHAPE="RECT" COORDS="73, 23, 79, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '339999');window.close()">
                <AREA SHAPE="RECT" COORDS="81, 23, 87, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '3399CC');window.close()">
                <AREA SHAPE="RECT" COORDS="89, 23, 95, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '3399FF');window.close()">
                <AREA SHAPE="RECT" COORDS="97, 23, 103, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '669900');window.close()">
                <AREA SHAPE="RECT" COORDS="105, 23, 111, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '669933');window.close()">
                <AREA SHAPE="RECT" COORDS="113, 23, 119, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '669966');window.close()">
                <AREA SHAPE="RECT" COORDS="121, 23, 127, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '669999');window.close()">
                <AREA SHAPE="RECT" COORDS="129, 23, 135, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '6699CC');window.close()">
                <AREA SHAPE="RECT" COORDS="137, 23, 143, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '6699FF');window.close()">
                <AREA SHAPE="RECT" COORDS="145, 23, 151, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '999900');window.close()">
                <AREA SHAPE="RECT" COORDS="153, 23, 159, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '999933');window.close()">
                <AREA SHAPE="RECT" COORDS="161, 23, 167, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '999966');window.close()">
                <AREA SHAPE="RECT" COORDS="169, 23, 175, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '999999');window.close()">
                <AREA SHAPE="RECT" COORDS="177, 23, 183, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '9999CC');window.close()">
                <AREA SHAPE="RECT" COORDS="185, 23, 191, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '9999FF');window.close()">
                <AREA SHAPE="RECT" COORDS="193, 23, 199, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC9900');window.close()">
                <AREA SHAPE="RECT" COORDS="201, 23, 207, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC9933');window.close()">
                <AREA SHAPE="RECT" COORDS="209, 23, 215, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC9966');window.close()">
                <AREA SHAPE="RECT" COORDS="217, 23, 223, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC9999');window.close()">
                <AREA SHAPE="RECT" COORDS="225, 23, 231, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC99CC');window.close()">
                <AREA SHAPE="RECT" COORDS="233, 23, 239, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC99FF');window.close()">
                <AREA SHAPE="RECT" COORDS="241, 23, 247, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF9900');window.close()">
                <AREA SHAPE="RECT" COORDS="249, 23, 255, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF9933');window.close()">
                <AREA SHAPE="RECT" COORDS="257, 23, 263, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF9966');window.close()">
                <AREA SHAPE="RECT" COORDS="265, 23, 271, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF9999');window.close()">
                <AREA SHAPE="RECT" COORDS="273, 23, 279, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF99CC');window.close()">
                <AREA SHAPE="RECT" COORDS="281, 23, 287, 32" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF99FF');window.close()">
                <AREA SHAPE="RECT" COORDS="1, 34, 7, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '006600');window.close()">
                <AREA SHAPE="RECT" COORDS="9, 34, 15, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '006633');window.close()">
                <AREA SHAPE="RECT" COORDS="17, 34, 23, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '006666');window.close()">
                <AREA SHAPE="RECT" COORDS="25, 34, 31, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '006699');window.close()">
                <AREA SHAPE="RECT" COORDS="33, 34, 39, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '0066CC');window.close()">
                <AREA SHAPE="RECT" COORDS="41, 34, 47, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '0066FF');window.close()">
                <AREA SHAPE="RECT" COORDS="49, 34, 55, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '336600');window.close()">
                <AREA SHAPE="RECT" COORDS="57, 34, 63, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '336633');window.close()">
                <AREA SHAPE="RECT" COORDS="65, 34, 71, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '336666');window.close()">
                <AREA SHAPE="RECT" COORDS="73, 34, 79, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '336699');window.close()">
                <AREA SHAPE="RECT" COORDS="81, 34, 87, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '3366CC');window.close()">
                <AREA SHAPE="RECT" COORDS="89, 34, 95, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '3366FF');window.close()">
                <AREA SHAPE="RECT" COORDS="97, 34, 103, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '666600');window.close()">
                <AREA SHAPE="RECT" COORDS="105, 34, 111, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '666633');window.close()">
                <AREA SHAPE="RECT" COORDS="113, 34, 119, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '666666');window.close()">
                <AREA SHAPE="RECT" COORDS="121, 34, 127, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '666699');window.close()">
                <AREA SHAPE="RECT" COORDS="129, 34, 135, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '6666CC');window.close()">
                <AREA SHAPE="RECT" COORDS="137, 34, 143, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '6666FF');window.close()">
                <AREA SHAPE="RECT" COORDS="145, 34, 151, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '996600');window.close()">
                <AREA SHAPE="RECT" COORDS="153, 34, 159, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '996633');window.close()">
                <AREA SHAPE="RECT" COORDS="161, 34, 167, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '996666');window.close()">
                <AREA SHAPE="RECT" COORDS="169, 34, 175, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '996699');window.close()">
                <AREA SHAPE="RECT" COORDS="177, 34, 183, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '9966CC');window.close()">
                <AREA SHAPE="RECT" COORDS="185, 34, 191, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '9966FF');window.close()">
                <AREA SHAPE="RECT" COORDS="193, 34, 199, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC6600');window.close()">
                <AREA SHAPE="RECT" COORDS="201, 34, 207, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC6633');window.close()">
                <AREA SHAPE="RECT" COORDS="209, 34, 215, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC6666');window.close()">
                <AREA SHAPE="RECT" COORDS="217, 34, 223, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC6699');window.close()">
                <AREA SHAPE="RECT" COORDS="225, 34, 231, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC66CC');window.close()">
                <AREA SHAPE="RECT" COORDS="233, 34, 239, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC66FF');window.close()">
                <AREA SHAPE="RECT" COORDS="241, 34, 247, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF6600');window.close()">
                <AREA SHAPE="RECT" COORDS="249, 34, 255, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF6633');window.close()">
                <AREA SHAPE="RECT" COORDS="257, 34, 263, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF6666');window.close()">
                <AREA SHAPE="RECT" COORDS="265, 34, 271, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF6699');window.close()">
                <AREA SHAPE="RECT" COORDS="273, 34, 279, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF66CC');window.close()">
                <AREA SHAPE="RECT" COORDS="281, 34, 287, 43" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF66FF');window.close()">
                <AREA SHAPE="RECT" COORDS="1, 45, 7, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '003300');window.close()">
                <AREA SHAPE="RECT" COORDS="9, 45, 15, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '003333');window.close()">
                <AREA SHAPE="RECT" COORDS="17, 45, 23, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '003366');window.close()">
                <AREA SHAPE="RECT" COORDS="25, 45, 31, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '003399');window.close()">
                <AREA SHAPE="RECT" COORDS="33, 45, 39, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '0033CC');window.close()">
                <AREA SHAPE="RECT" COORDS="41, 45, 47, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '0033FF');window.close()">
                <AREA SHAPE="RECT" COORDS="49, 45, 55, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '333300');window.close()">
                <AREA SHAPE="RECT" COORDS="57, 45, 63, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '333333');window.close()">
                <AREA SHAPE="RECT" COORDS="65, 45, 71, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '333366');window.close()">
                <AREA SHAPE="RECT" COORDS="73, 45, 79, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '333399');window.close()">
                <AREA SHAPE="RECT" COORDS="81, 45, 87, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '3333CC');window.close()">
                <AREA SHAPE="RECT" COORDS="89, 45, 95, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '3333FF');window.close()">
                <AREA SHAPE="RECT" COORDS="97, 45, 103, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '663300');window.close()">
                <AREA SHAPE="RECT" COORDS="105, 45, 111, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '663333');window.close()">
                <AREA SHAPE="RECT" COORDS="113, 45, 119, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '663366');window.close()">
                <AREA SHAPE="RECT" COORDS="121, 45, 127, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '663399');window.close()">
                <AREA SHAPE="RECT" COORDS="129, 45, 135, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '6633CC');window.close()">
                <AREA SHAPE="RECT" COORDS="137, 45, 143, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '6633FF');window.close()">
                <AREA SHAPE="RECT" COORDS="145, 45, 151, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '993300');window.close()">
                <AREA SHAPE="RECT" COORDS="153, 45, 159, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '993333');window.close()">
                <AREA SHAPE="RECT" COORDS="161, 45, 167, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '993366');window.close()">
                <AREA SHAPE="RECT" COORDS="169, 45, 175, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '993399');window.close()">
                <AREA SHAPE="RECT" COORDS="177, 45, 183, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '9933CC');window.close()">
                <AREA SHAPE="RECT" COORDS="185, 45, 191, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '9933FF');window.close()">
                <AREA SHAPE="RECT" COORDS="193, 45, 199, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC3300');window.close()">
                <AREA SHAPE="RECT" COORDS="201, 45, 207, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC3333');window.close()">
                <AREA SHAPE="RECT" COORDS="209, 45, 215, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC3366');window.close()">
                <AREA SHAPE="RECT" COORDS="217, 45, 223, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC3399');window.close()">
                <AREA SHAPE="RECT" COORDS="225, 45, 231, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC33CC');window.close()">
                <AREA SHAPE="RECT" COORDS="233, 45, 239, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC33FF');window.close()">
                <AREA SHAPE="RECT" COORDS="241, 45, 247, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF3300');window.close()">
                <AREA SHAPE="RECT" COORDS="249, 45, 255, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF3333');window.close()">
                <AREA SHAPE="RECT" COORDS="257, 45, 263, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF3366');window.close()">
                <AREA SHAPE="RECT" COORDS="265, 45, 271, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF3399');window.close()">
                <AREA SHAPE="RECT" COORDS="273, 45, 279, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF33CC');window.close()">
                <AREA SHAPE="RECT" COORDS="281, 45, 287, 54" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF33FF');window.close()">
                <AREA SHAPE="RECT" COORDS="1, 56, 7, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '000000');window.close()">
                <AREA SHAPE="RECT" COORDS="9, 56, 15, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '000033');window.close()">
                <AREA SHAPE="RECT" COORDS="17, 56, 23, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '000066');window.close()">
                <AREA SHAPE="RECT" COORDS="25, 56, 31, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '000099');window.close()">
                <AREA SHAPE="RECT" COORDS="33, 56, 39, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '0000CC');window.close()">
                <AREA SHAPE="RECT" COORDS="41, 56, 47, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '0000FF');window.close()">
                <AREA SHAPE="RECT" COORDS="49, 56, 55, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '330000');window.close()">
                <AREA SHAPE="RECT" COORDS="57, 56, 63, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '330033');window.close()">
                <AREA SHAPE="RECT" COORDS="65, 56, 71, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '330066');window.close()">
                <AREA SHAPE="RECT" COORDS="73, 56, 79, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '330099');window.close()">
                <AREA SHAPE="RECT" COORDS="81, 56, 87, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '3300CC');window.close()">
                <AREA SHAPE="RECT" COORDS="89, 56, 95, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '3300FF');window.close()">
                <AREA SHAPE="RECT" COORDS="97, 56, 103, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '660000');window.close()">
                <AREA SHAPE="RECT" COORDS="105, 56, 111, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '660033');window.close()">
                <AREA SHAPE="RECT" COORDS="113, 56, 119, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '660066');window.close()">
                <AREA SHAPE="RECT" COORDS="121, 56, 127, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '660099');window.close()">
                <AREA SHAPE="RECT" COORDS="129, 56, 135, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '6600CC');window.close()">
                <AREA SHAPE="RECT" COORDS="137, 56, 143, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '6600FF');window.close()">
                <AREA SHAPE="RECT" COORDS="145, 56, 151, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '990000');window.close()">
                <AREA SHAPE="RECT" COORDS="153, 56, 159, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '990033');window.close()">
                <AREA SHAPE="RECT" COORDS="161, 56, 167, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '990066');window.close()">
                <AREA SHAPE="RECT" COORDS="169, 56, 175, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '990099');window.close()">
                <AREA SHAPE="RECT" COORDS="177, 56, 183, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '9900CC');window.close()">
                <AREA SHAPE="RECT" COORDS="185, 56, 191, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', '9900FF');window.close()">
                <AREA SHAPE="RECT" COORDS="193, 56, 199, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC0000');window.close()">
                <AREA SHAPE="RECT" COORDS="201, 56, 207, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC0033');window.close()">
                <AREA SHAPE="RECT" COORDS="209, 56, 215, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC0066');window.close()">
                <AREA SHAPE="RECT" COORDS="217, 56, 223, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC0099');window.close()">
                <AREA SHAPE="RECT" COORDS="225, 56, 231, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC00CC');window.close()">
                <AREA SHAPE="RECT" COORDS="233, 56, 239, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'CC00FF');window.close()">
                <AREA SHAPE="RECT" COORDS="241, 56, 247, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF0000');window.close()">
                <AREA SHAPE="RECT" COORDS="249, 56, 255, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF0033');window.close()">
                <AREA SHAPE="RECT" COORDS="257, 56, 263, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF0066');window.close()">
                <AREA SHAPE="RECT" COORDS="265, 56, 271, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF0099');window.close()">
                <AREA SHAPE="RECT" COORDS="273, 56, 279, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF00CC');window.close()">
                <AREA SHAPE="RECT" COORDS="281, 56, 287, 65" HREF="javascript:opener.traercolor('<cfoutput>#url.obj#</cfoutput>', '<cfoutput>#url.tabla#</cfoutput>', 'FF00FF');window.close()">
            </MAP>
            <img src="colortable.gif" border="0" width="289" height="67" usemap="#FrontPageMap0">
        </form>
    </body>
</html>

