/*
 * Generated by JasperReports - 21/07/04 03:08 PM
 */
import dori.jasper.engine.*;
import dori.jasper.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class SolicitudCot extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_fecha = null;
    private JRFillParameter parameter_Edescripcion = null;
    private JRFillParameter parameter_Ecodigo = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;

    private JRFillField field_EOnumero = null;
    private JRFillField field_Edescripcion = null;
    private JRFillField field_DOcantidad = null;
    private JRFillField field_Mnombre = null;
    private JRFillField field_EOfecha = null;
    private JRFillField field_DOlinea = null;
    private JRFillField field_Msimbolo = null;
    private JRFillField field_SNnombre = null;
    private JRFillField field_Descripcion = null;
    private JRFillField field_Ucodigo = null;
    private JRFillField field_SNFax = null;
    private JRFillField field_Aid = null;
    private JRFillField field_SNtelefono = null;
    private JRFillField field_ESidsolicitud = null;
    private JRFillField field_DOpreciou = null;
    private JRFillField field_DOtotal = null;
    private JRFillField field_EOplazo = null;
    private JRFillField field_SNdireccion = null;
    private JRFillField field_DOdescripcion = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_fecha = (JRFillParameter)parsm.get("fecha");
        parameter_Edescripcion = (JRFillParameter)parsm.get("Edescripcion");
        parameter_Ecodigo = (JRFillParameter)parsm.get("Ecodigo");
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");

        field_EOnumero = (JRFillField)fldsm.get("EOnumero");
        field_Edescripcion = (JRFillField)fldsm.get("Edescripcion");
        field_DOcantidad = (JRFillField)fldsm.get("DOcantidad");
        field_Mnombre = (JRFillField)fldsm.get("Mnombre");
        field_EOfecha = (JRFillField)fldsm.get("EOfecha");
        field_DOlinea = (JRFillField)fldsm.get("DOlinea");
        field_Msimbolo = (JRFillField)fldsm.get("Msimbolo");
        field_SNnombre = (JRFillField)fldsm.get("SNnombre");
        field_Descripcion = (JRFillField)fldsm.get("Descripcion");
        field_Ucodigo = (JRFillField)fldsm.get("Ucodigo");
        field_SNFax = (JRFillField)fldsm.get("SNFax");
        field_Aid = (JRFillField)fldsm.get("Aid");
        field_SNtelefono = (JRFillField)fldsm.get("SNtelefono");
        field_ESidsolicitud = (JRFillField)fldsm.get("ESidsolicitud");
        field_DOpreciou = (JRFillField)fldsm.get("DOpreciou");
        field_DOtotal = (JRFillField)fldsm.get("DOtotal");
        field_EOplazo = (JRFillField)fldsm.get("EOplazo");
        field_SNdireccion = (JRFillField)fldsm.get("SNdireccion");
        field_DOdescripcion = (JRFillField)fldsm.get("DOdescripcion");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 3967 : // printWhen_37
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4004 : // printWhen_60
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3992 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)field_Descripcion.getValue()));
                break;
            }
            case 3993 : // textField_15
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOpreciou.getValue()));
                break;
            }
            case 3974 : // printWhen_41
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3932 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3947 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3948 : // textField_6
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 3913 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3996 : // textField_18
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOtotal.getValue()));
                break;
            }
            case 3953 : // printWhen_23
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4006 : // printWhen_62
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3963 : // printWhen_33
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3945 : // textField_5
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 3939 : // textField_4
            {
                value = (java.lang.Double)(((java.lang.Double)field_EOnumero.getValue()));
                break;
            }
            case 4007 : // textField_22
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 3950 : // textField_7
            {
                value = (java.util.Date)(((java.util.Date)field_EOfecha.getValue()));
                break;
            }
            case 3918 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3980 : // printWhen_45
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3934 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3997 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)field_Ucodigo.getValue()));
                break;
            }
            case 3956 : // printWhen_26
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3924 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3942 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3955 : // printWhen_25
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3969 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_SNdireccion.getValue()));
                break;
            }
            case 3994 : // textField_16
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Aid.getValue()));
                break;
            }
            case 3929 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3973 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 3983 : // printWhen_48
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4005 : // printWhen_61
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3933 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_SNtelefono.getValue()));
                break;
            }
            case 3986 : // printWhen_51
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3926 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) == null));
                break;
            }
            case 3920 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3921 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 3949 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3998 : // textField_20
            {
                value = (java.lang.Float)(((java.lang.Float)field_DOcantidad.getValue()));
                break;
            }
            case 3982 : // printWhen_47
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3972 : // printWhen_40
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3999 : // textField_21
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOlinea.getValue()));
                break;
            }
            case 3970 : // printWhen_39
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3975 : // textField_11
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_EOplazo.getValue()));
                break;
            }
            case 3961 : // printWhen_31
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3952 : // printWhen_22
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3919 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3971 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_SNnombre.getValue()));
                break;
            }
            case 3968 : // printWhen_38
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3964 : // printWhen_34
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3957 : // printWhen_27
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3959 : // printWhen_29
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3923 : // parameterDefaultValue_fecha
            {
                value = (java.lang.String)(new java.lang.String("31/12/2004"));
                break;
            }
            case 3940 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3989 : // printWhen_54
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3990 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)field_Msimbolo.getValue()));
                break;
            }
            case 3976 : // printWhen_42
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3981 : // printWhen_46
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3916 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3930 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 3979 : // printWhen_44
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3943 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3987 : // printWhen_52
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4001 : // printWhen_57
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3954 : // printWhen_24
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3946 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3914 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3995 : // textField_17
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOlinea.getValue()));
                break;
            }
            case 3941 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4003 : // printWhen_59
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3984 : // printWhen_49
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3978 : // printWhen_43
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3988 : // printWhen_53
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4002 : // printWhen_58
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3927 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3991 : // printWhen_55
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3917 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3936 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3977 : // textField_12
            {
                value = (java.lang.String)("Enviar documentos vía  courier");
                break;
            }
            case 3960 : // printWhen_30
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3965 : // printWhen_35
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4000 : // printWhen_56
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3951 : // printWhen_21
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3935 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_SNFax.getValue()));
                break;
            }
            case 3958 : // printWhen_28
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3962 : // printWhen_32
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3915 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3925 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3966 : // printWhen_36
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3938 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3937 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3944 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3985 : // printWhen_50
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3928 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3931 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3922 : // parameterDefaultValue_Edescripcion
            {
                value = (java.lang.String)(new java.lang.String("Empresa de Prueba"));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 3967 : // printWhen_37
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 4004 : // printWhen_60
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3992 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)field_Descripcion.getOldValue()));
                break;
            }
            case 3993 : // textField_15
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOpreciou.getOldValue()));
                break;
            }
            case 3974 : // printWhen_41
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3932 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3947 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3948 : // textField_6
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 3913 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3996 : // textField_18
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOtotal.getOldValue()));
                break;
            }
            case 3953 : // printWhen_23
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 4006 : // printWhen_62
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3963 : // printWhen_33
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3945 : // textField_5
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 3939 : // textField_4
            {
                value = (java.lang.Double)(((java.lang.Double)field_EOnumero.getOldValue()));
                break;
            }
            case 4007 : // textField_22
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getOldValue()));
                break;
            }
            case 3950 : // textField_7
            {
                value = (java.util.Date)(((java.util.Date)field_EOfecha.getOldValue()));
                break;
            }
            case 3918 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3980 : // printWhen_45
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3934 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3997 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)field_Ucodigo.getOldValue()));
                break;
            }
            case 3956 : // printWhen_26
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3924 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3942 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3955 : // printWhen_25
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3969 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_SNdireccion.getOldValue()));
                break;
            }
            case 3994 : // textField_16
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Aid.getOldValue()));
                break;
            }
            case 3929 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3973 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getOldValue()));
                break;
            }
            case 3983 : // printWhen_48
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 4005 : // printWhen_61
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3933 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_SNtelefono.getOldValue()));
                break;
            }
            case 3986 : // printWhen_51
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3926 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) == null));
                break;
            }
            case 3920 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3921 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 3949 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3998 : // textField_20
            {
                value = (java.lang.Float)(((java.lang.Float)field_DOcantidad.getOldValue()));
                break;
            }
            case 3982 : // printWhen_47
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3972 : // printWhen_40
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3999 : // textField_21
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOlinea.getOldValue()));
                break;
            }
            case 3970 : // printWhen_39
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3975 : // textField_11
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_EOplazo.getOldValue()));
                break;
            }
            case 3961 : // printWhen_31
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3952 : // printWhen_22
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3919 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3971 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_SNnombre.getOldValue()));
                break;
            }
            case 3968 : // printWhen_38
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3964 : // printWhen_34
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3957 : // printWhen_27
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3959 : // printWhen_29
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3923 : // parameterDefaultValue_fecha
            {
                value = (java.lang.String)(new java.lang.String("31/12/2004"));
                break;
            }
            case 3940 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3989 : // printWhen_54
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3990 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)field_Msimbolo.getOldValue()));
                break;
            }
            case 3976 : // printWhen_42
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3981 : // printWhen_46
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3916 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3930 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getOldValue()));
                break;
            }
            case 3979 : // printWhen_44
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3943 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3987 : // printWhen_52
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 4001 : // printWhen_57
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3954 : // printWhen_24
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3946 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3914 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3995 : // textField_17
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOlinea.getOldValue()));
                break;
            }
            case 3941 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 4003 : // printWhen_59
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3984 : // printWhen_49
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3978 : // printWhen_43
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3988 : // printWhen_53
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 4002 : // printWhen_58
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3927 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3991 : // printWhen_55
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3917 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3936 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3977 : // textField_12
            {
                value = (java.lang.String)("Enviar documentos vía  courier");
                break;
            }
            case 3960 : // printWhen_30
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3965 : // printWhen_35
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 4000 : // printWhen_56
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3951 : // printWhen_21
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3935 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_SNFax.getOldValue()));
                break;
            }
            case 3958 : // printWhen_28
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3962 : // printWhen_32
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3915 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3925 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3966 : // printWhen_36
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3938 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3937 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3944 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3985 : // printWhen_50
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3928 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3931 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 3922 : // parameterDefaultValue_Edescripcion
            {
                value = (java.lang.String)(new java.lang.String("Empresa de Prueba"));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 3967 : // printWhen_37
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4004 : // printWhen_60
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3992 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)field_Descripcion.getValue()));
                break;
            }
            case 3993 : // textField_15
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOpreciou.getValue()));
                break;
            }
            case 3974 : // printWhen_41
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3932 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3947 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3948 : // textField_6
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 3913 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3996 : // textField_18
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOtotal.getValue()));
                break;
            }
            case 3953 : // printWhen_23
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4006 : // printWhen_62
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3963 : // printWhen_33
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3945 : // textField_5
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 3939 : // textField_4
            {
                value = (java.lang.Double)(((java.lang.Double)field_EOnumero.getValue()));
                break;
            }
            case 4007 : // textField_22
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 3950 : // textField_7
            {
                value = (java.util.Date)(((java.util.Date)field_EOfecha.getValue()));
                break;
            }
            case 3918 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3980 : // printWhen_45
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3934 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3997 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)field_Ucodigo.getValue()));
                break;
            }
            case 3956 : // printWhen_26
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3924 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3942 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3955 : // printWhen_25
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3969 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_SNdireccion.getValue()));
                break;
            }
            case 3994 : // textField_16
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Aid.getValue()));
                break;
            }
            case 3929 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3973 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 3983 : // printWhen_48
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4005 : // printWhen_61
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3933 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_SNtelefono.getValue()));
                break;
            }
            case 3986 : // printWhen_51
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3926 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) == null));
                break;
            }
            case 3920 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3921 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 3949 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3998 : // textField_20
            {
                value = (java.lang.Float)(((java.lang.Float)field_DOcantidad.getValue()));
                break;
            }
            case 3982 : // printWhen_47
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3972 : // printWhen_40
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3999 : // textField_21
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOlinea.getValue()));
                break;
            }
            case 3970 : // printWhen_39
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3975 : // textField_11
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_EOplazo.getValue()));
                break;
            }
            case 3961 : // printWhen_31
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3952 : // printWhen_22
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3919 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3971 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_SNnombre.getValue()));
                break;
            }
            case 3968 : // printWhen_38
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3964 : // printWhen_34
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3957 : // printWhen_27
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3959 : // printWhen_29
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3923 : // parameterDefaultValue_fecha
            {
                value = (java.lang.String)(new java.lang.String("31/12/2004"));
                break;
            }
            case 3940 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3989 : // printWhen_54
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3990 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)field_Msimbolo.getValue()));
                break;
            }
            case 3976 : // printWhen_42
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3981 : // printWhen_46
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3916 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 3930 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 3979 : // printWhen_44
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3943 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3987 : // printWhen_52
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4001 : // printWhen_57
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3954 : // printWhen_24
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3946 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3914 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3995 : // textField_17
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_DOlinea.getValue()));
                break;
            }
            case 3941 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4003 : // printWhen_59
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3984 : // printWhen_49
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3978 : // printWhen_43
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3988 : // printWhen_53
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4002 : // printWhen_58
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3927 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3991 : // printWhen_55
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3917 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3936 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3977 : // textField_12
            {
                value = (java.lang.String)("Enviar documentos vía  courier");
                break;
            }
            case 3960 : // printWhen_30
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3965 : // printWhen_35
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 4000 : // printWhen_56
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3951 : // printWhen_21
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3935 : // textField_3
            {
                value = (java.lang.String)(((java.lang.String)field_SNFax.getValue()));
                break;
            }
            case 3958 : // printWhen_28
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3962 : // printWhen_32
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3915 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3925 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3966 : // printWhen_36
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3938 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3937 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3944 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3985 : // printWhen_50
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3928 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3931 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 3922 : // parameterDefaultValue_Edescripcion
            {
                value = (java.lang.String)(new java.lang.String("Empresa de Prueba"));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
