<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_Esta_seguro_que_desea_Eliminar_los_Registros_Seleccionados_Si_elimina_los_registros_seleccionados_eliminara_todos_los_datos_relacionados_con_la_nomina_y_tendra_que_recalcular_la_nomina"
	Default="¿Está seguro que desea Eliminar los Registros Seleccionados?\n\nSi elimina los registros seleccionados, eliminará todos los datos relacionados con la nómina \ny tendrá que recalcular la nómina."	
	returnvariable="LB_ElimarRegistrosSeleccionados"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_Seleccione_el_Registro_que_desea_eliminar"
	Default="¡Seleccione el Registro que desea eliminar!"	
	returnvariable="LB_SeleccionarRegistros"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_No_se_pueden_crear_nuevas_relaciones_de_calculo_de_nomina_porque_no_hay_calendarios_de_pago_definidos"
	Default="No se pueden crear nuevas relaciones de cálculo de nómina porque no hay calendarios de pago definidos"	
	returnvariable="LB_NoCalendariosDefinidos"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_Tipo_de_nomina"
	Default="Tipo de nómina"	
	returnvariable="LB_Tipo_de_nomina"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_Codigo_Calendario"
	Default="Código Calendario"	
	returnvariable="LB_Codigo_Calendario"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_Relacion_de_Calculo"
	Default="Relación de Cálculo"	
	returnvariable="LB_Relacion_de_Calculo"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_Fecha_Inicio"
	Default="Fecha Inicio"	
	XmlFile="/rh/generales.xml"
	returnvariable="LB_Fecha_Inicio"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_Fecha_Hasta"
	Default="Fecha Hasta"	
	XmlFile="/rh/generales.xml"
	returnvariable="LB_Fecha_Hasta"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_Estado"
	Default="Estado"	
	returnvariable="LB_Estado"/>
<!---Boton Eliminar ---->
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="BTN_Eliminar"
	Default="Eliminar"
	XmlFile="/rh/generales.xml"
	returnvariable="BTN_Eliminar"/>
<!----Boton Nuevo ---->
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="BTN_Nuevo"
	Default="Nuevo"
	XmlFile="/rh/generales.xml"
	returnvariable="BTN_Nuevo"/>
<cfinvoke Default="Relaciones de C&aacute;lculo Especiales" VSgrupo="103" returnvariable="nombre_proceso" component="sif.Componentes.TranslateDB" method="Translate" VSvalor="#session.monitoreo.SScodigo#.#session.monitoreo.SMcodigo#.#session.monitoreo.SPcodigo#"/>
<!---=============== TRADUCCION ===================---->
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="MSG_No_quedan_calendarios_de_pago_para_el_tipo_de_Nomina_seleccionado"
	Default="No quedan calendarios de pago para el tipo de Nómina seleccionado"	
	returnvariable="MSG_NoHayCalendariosPago"/>
<!---Boton de aplicar ---->
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="BTN_Aplicar"
	Default="Aplicar"	
	xmlfile="/rh/generales.xml"
	returnvariable="BTN_Aplicar"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="MSG_No_puede_ser_cero"
	Default="no puede ser cero!"	
	returnvariable="MSG_No_puede_ser_cero"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="MSG_Descripcion"
	Default="Descripción"	
	returnvariable="MSG_Descripcion"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="MSG_Tipo_de_Nomina"
	Default="Tipo de Nómina"	
	returnvariable="MSG_Tipo_de_Nomina"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="MSG_Fecha_Desde"
	Default="Fecha Desde"	
	returnvariable="MSG_Fecha_Desde"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="MSG_Fecha_Hasta"
	Default="Fecha Hasta"	
	returnvariable="MSG_Fecha_Hasta"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="MSG_Porcentaje_incorrecto"
	Default="El porcentaje no puede ser mayor a 100."	
	returnvariable="MSG_Porcentaje_incorrecto"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="MSG_Porcentaje"
	Default="Porcentaje"
	returnvariable="MSG_Porcentaje"/>
<cfinvoke component="sif.Componentes.Translate"
	method="Translate"
	Key="LB_Concepto_Incidente"
	Default="Concepto Incidente"
	returnvariable="LB_Concepto_Incidente"
	xmlfile="/rh/nomina//operacion/Incidencias.xml"/>
