/*
 * Generated by JasperReports - 14/07/04 11:29 PM
 */
import dori.jasper.engine.*;
import dori.jasper.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class classic_landscape extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_fechaIniLabel = null;
    private JRFillParameter parameter_Ecodigo = null;
    private JRFillParameter parameter_CCTcodigo = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_SNcodigo = null;
    private JRFillParameter parameter_DdocumentoLabel = null;
    private JRFillParameter parameter_BMfecha = null;
    private JRFillParameter parameter_Ddocumento = null;
    private JRFillParameter parameter_SNnombre = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;

    private JRFillField field_Dtipocambio = null;
    private JRFillField field_Mnombre = null;
    private JRFillField field_Ecodigo = null;
    private JRFillField field_Edescripcion = null;
    private JRFillField field_Mcodigo = null;
    private JRFillField field_Odescripcion = null;
    private JRFillField field_BMtref = null;
    private JRFillField field_Dtotalloc = null;
    private JRFillField field_CCTdescripcion = null;
    private JRFillField field_SNnombre = null;
    private JRFillField field_tipo = null;
    private JRFillField field_BMdocref = null;
    private JRFillField field_CCTcodigo = null;
    private JRFillField field_SNcodigo = null;
    private JRFillField field_BMfecha = null;
    private JRFillField field_Ddocumento = null;
    private JRFillField field_Dtotal = null;
    private JRFillField field_fecha_hora = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_test = null;
    private JRFillVariable variable_TotalMoneda = null;
    private JRFillVariable variable_TotalCliente = null;
    private JRFillVariable variable_TotalDoc = null;
    private JRFillVariable variable_TotalMonedaLoc = null;
    private JRFillVariable variable_TotalDocLoc = null;
    private JRFillVariable variable_SNcodigo_COUNT = null;
    private JRFillVariable variable_Mcodigo_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_fechaIniLabel = (JRFillParameter)parsm.get("fechaIniLabel");
        parameter_Ecodigo = (JRFillParameter)parsm.get("Ecodigo");
        parameter_CCTcodigo = (JRFillParameter)parsm.get("CCTcodigo");
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_SNcodigo = (JRFillParameter)parsm.get("SNcodigo");
        parameter_DdocumentoLabel = (JRFillParameter)parsm.get("DdocumentoLabel");
        parameter_BMfecha = (JRFillParameter)parsm.get("BMfecha");
        parameter_Ddocumento = (JRFillParameter)parsm.get("Ddocumento");
        parameter_SNnombre = (JRFillParameter)parsm.get("SNnombre");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");

        field_Dtipocambio = (JRFillField)fldsm.get("Dtipocambio");
        field_Mnombre = (JRFillField)fldsm.get("Mnombre");
        field_Ecodigo = (JRFillField)fldsm.get("Ecodigo");
        field_Edescripcion = (JRFillField)fldsm.get("Edescripcion");
        field_Mcodigo = (JRFillField)fldsm.get("Mcodigo");
        field_Odescripcion = (JRFillField)fldsm.get("Odescripcion");
        field_BMtref = (JRFillField)fldsm.get("BMtref");
        field_Dtotalloc = (JRFillField)fldsm.get("Dtotalloc");
        field_CCTdescripcion = (JRFillField)fldsm.get("CCTdescripcion");
        field_SNnombre = (JRFillField)fldsm.get("SNnombre");
        field_tipo = (JRFillField)fldsm.get("tipo");
        field_BMdocref = (JRFillField)fldsm.get("BMdocref");
        field_CCTcodigo = (JRFillField)fldsm.get("CCTcodigo");
        field_SNcodigo = (JRFillField)fldsm.get("SNcodigo");
        field_BMfecha = (JRFillField)fldsm.get("BMfecha");
        field_Ddocumento = (JRFillField)fldsm.get("Ddocumento");
        field_Dtotal = (JRFillField)fldsm.get("Dtotal");
        field_fecha_hora = (JRFillField)fldsm.get("fecha_hora");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_test = (JRFillVariable)varsm.get("test");
        variable_TotalMoneda = (JRFillVariable)varsm.get("TotalMoneda");
        variable_TotalCliente = (JRFillVariable)varsm.get("TotalCliente");
        variable_TotalDoc = (JRFillVariable)varsm.get("TotalDoc");
        variable_TotalMonedaLoc = (JRFillVariable)varsm.get("TotalMonedaLoc");
        variable_TotalDocLoc = (JRFillVariable)varsm.get("TotalDocLoc");
        variable_SNcodigo_COUNT = (JRFillVariable)varsm.get("SNcodigo_COUNT");
        variable_Mcodigo_COUNT = (JRFillVariable)varsm.get("Mcodigo_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 2304 : // variableInitialValue_Mcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2294 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_SNnombre.getValue()));
                break;
            }
            case 2281 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 2278 : // parameterDefaultValue_Ddocumento
            {
                value = (java.lang.String)("Todos");
                break;
            }
            case 2265 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2303 : // variable_Mcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2267 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2275 : // parameterDefaultValue_BMfecha
            {
                value = (java.lang.String)("31/12/2003");
                break;
            }
            case 2306 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)parameter_SNnombre.getValue()));
                break;
            }
            case 2300 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_Mnombre.getValue()));
                break;
            }
            case 2266 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2316 : // textField_18
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 2291 : // variable_TotalDocLoc
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getValue()));
                break;
            }
            case 2276 : // parameterDefaultValue_SNnombre
            {
                value = (java.lang.String)("Todos");
                break;
            }
            case 2274 : // parameterDefaultValue_SNcodigo
            {
                value = (java.lang.Integer)(new java.lang.Integer(-1));
                break;
            }
            case 2271 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2288 : // variableInitialValue_TotalDoc
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2299 : // group_Mcodigo
            {
                value = (java.lang.Object)(((java.lang.Double)field_Mcodigo.getValue()));
                break;
            }
            case 2272 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2308 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)parameter_DdocumentoLabel.getValue()));
                break;
            }
            case 2279 : // parameterDefaultValue_DdocumentoLabel
            {
                value = (java.lang.String)("Todos");
                break;
            }
            case 2293 : // group_SNcodigo
            {
                value = (java.lang.Object)(((java.lang.Integer)field_SNcodigo.getValue()));
                break;
            }
            case 2298 : // variableInitialValue_SNcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2269 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2295 : // textField_2
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_SNcodigo.getValue()));
                break;
            }
            case 2287 : // variable_TotalDoc
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotal.getValue()));
                break;
            }
            case 2289 : // variable_TotalMonedaLoc
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getValue()));
                break;
            }
            case 2273 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 2301 : // textField_5
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalMoneda.getValue()));
                break;
            }
            case 2286 : // variableInitialValue_TotalCliente
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2302 : // textField_6
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalMonedaLoc.getValue()));
                break;
            }
            case 2292 : // variableInitialValue_TotalDocLoc
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2285 : // variable_TotalCliente
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getValue()));
                break;
            }
            case 2268 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2297 : // variable_SNcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2282 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 2280 : // parameterDefaultValue_CCTcodigo
            {
                value = (java.lang.String)(new java.lang.String("-1"));
                break;
            }
            case 2284 : // variableInitialValue_TotalMoneda
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2312 : // textField_14
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotal.getValue()));
                break;
            }
            case 2277 : // parameterDefaultValue_fechaIniLabel
            {
                value = (java.lang.String)("Todas");
                break;
            }
            case 2305 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 2311 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)field_BMfecha.getValue()));
                break;
            }
            case 2313 : // textField_15
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getValue()));
                break;
            }
            case 2296 : // textField_3
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalCliente.getValue()));
                break;
            }
            case 2270 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2315 : // textField_17
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " of ");
                break;
            }
            case 2307 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)parameter_fechaIniLabel.getValue()));
                break;
            }
            case 2310 : // textField_12
            {
                value = (java.lang.String)(((java.lang.String)field_Ddocumento.getValue()));
                break;
            }
            case 2309 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)field_tipo.getValue()));
                break;
            }
            case 2283 : // variable_TotalMoneda
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotal.getValue()));
                break;
            }
            case 2314 : // textField_16
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtipocambio.getValue()));
                break;
            }
            case 2290 : // variableInitialValue_TotalMonedaLoc
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2317 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)field_fecha_hora.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 2304 : // variableInitialValue_Mcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2294 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_SNnombre.getOldValue()));
                break;
            }
            case 2281 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 2278 : // parameterDefaultValue_Ddocumento
            {
                value = (java.lang.String)("Todos");
                break;
            }
            case 2265 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2303 : // variable_Mcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2267 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2275 : // parameterDefaultValue_BMfecha
            {
                value = (java.lang.String)("31/12/2003");
                break;
            }
            case 2306 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)parameter_SNnombre.getValue()));
                break;
            }
            case 2300 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_Mnombre.getOldValue()));
                break;
            }
            case 2266 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2316 : // textField_18
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 2291 : // variable_TotalDocLoc
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getOldValue()));
                break;
            }
            case 2276 : // parameterDefaultValue_SNnombre
            {
                value = (java.lang.String)("Todos");
                break;
            }
            case 2274 : // parameterDefaultValue_SNcodigo
            {
                value = (java.lang.Integer)(new java.lang.Integer(-1));
                break;
            }
            case 2271 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2288 : // variableInitialValue_TotalDoc
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2299 : // group_Mcodigo
            {
                value = (java.lang.Object)(((java.lang.Double)field_Mcodigo.getOldValue()));
                break;
            }
            case 2272 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2308 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)parameter_DdocumentoLabel.getValue()));
                break;
            }
            case 2279 : // parameterDefaultValue_DdocumentoLabel
            {
                value = (java.lang.String)("Todos");
                break;
            }
            case 2293 : // group_SNcodigo
            {
                value = (java.lang.Object)(((java.lang.Integer)field_SNcodigo.getOldValue()));
                break;
            }
            case 2298 : // variableInitialValue_SNcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2269 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2295 : // textField_2
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_SNcodigo.getOldValue()));
                break;
            }
            case 2287 : // variable_TotalDoc
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotal.getOldValue()));
                break;
            }
            case 2289 : // variable_TotalMonedaLoc
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getOldValue()));
                break;
            }
            case 2273 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 2301 : // textField_5
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalMoneda.getOldValue()));
                break;
            }
            case 2286 : // variableInitialValue_TotalCliente
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2302 : // textField_6
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalMonedaLoc.getOldValue()));
                break;
            }
            case 2292 : // variableInitialValue_TotalDocLoc
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2285 : // variable_TotalCliente
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getOldValue()));
                break;
            }
            case 2268 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2297 : // variable_SNcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2282 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 2280 : // parameterDefaultValue_CCTcodigo
            {
                value = (java.lang.String)(new java.lang.String("-1"));
                break;
            }
            case 2284 : // variableInitialValue_TotalMoneda
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2312 : // textField_14
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotal.getOldValue()));
                break;
            }
            case 2277 : // parameterDefaultValue_fechaIniLabel
            {
                value = (java.lang.String)("Todas");
                break;
            }
            case 2305 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getOldValue()));
                break;
            }
            case 2311 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)field_BMfecha.getOldValue()));
                break;
            }
            case 2313 : // textField_15
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getOldValue()));
                break;
            }
            case 2296 : // textField_3
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalCliente.getOldValue()));
                break;
            }
            case 2270 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2315 : // textField_17
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " of ");
                break;
            }
            case 2307 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)parameter_fechaIniLabel.getValue()));
                break;
            }
            case 2310 : // textField_12
            {
                value = (java.lang.String)(((java.lang.String)field_Ddocumento.getOldValue()));
                break;
            }
            case 2309 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)field_tipo.getOldValue()));
                break;
            }
            case 2283 : // variable_TotalMoneda
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotal.getOldValue()));
                break;
            }
            case 2314 : // textField_16
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtipocambio.getOldValue()));
                break;
            }
            case 2290 : // variableInitialValue_TotalMonedaLoc
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2317 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)field_fecha_hora.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 2304 : // variableInitialValue_Mcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2294 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_SNnombre.getValue()));
                break;
            }
            case 2281 : // variable_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 2278 : // parameterDefaultValue_Ddocumento
            {
                value = (java.lang.String)("Todos");
                break;
            }
            case 2265 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2303 : // variable_Mcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2267 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2275 : // parameterDefaultValue_BMfecha
            {
                value = (java.lang.String)("31/12/2003");
                break;
            }
            case 2306 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)parameter_SNnombre.getValue()));
                break;
            }
            case 2300 : // textField_4
            {
                value = (java.lang.String)(((java.lang.String)field_Mnombre.getValue()));
                break;
            }
            case 2266 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2316 : // textField_18
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 2291 : // variable_TotalDocLoc
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getValue()));
                break;
            }
            case 2276 : // parameterDefaultValue_SNnombre
            {
                value = (java.lang.String)("Todos");
                break;
            }
            case 2274 : // parameterDefaultValue_SNcodigo
            {
                value = (java.lang.Integer)(new java.lang.Integer(-1));
                break;
            }
            case 2271 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2288 : // variableInitialValue_TotalDoc
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2299 : // group_Mcodigo
            {
                value = (java.lang.Object)(((java.lang.Double)field_Mcodigo.getValue()));
                break;
            }
            case 2272 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2308 : // textField_10
            {
                value = (java.lang.String)(((java.lang.String)parameter_DdocumentoLabel.getValue()));
                break;
            }
            case 2279 : // parameterDefaultValue_DdocumentoLabel
            {
                value = (java.lang.String)("Todos");
                break;
            }
            case 2293 : // group_SNcodigo
            {
                value = (java.lang.Object)(((java.lang.Integer)field_SNcodigo.getValue()));
                break;
            }
            case 2298 : // variableInitialValue_SNcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2269 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2295 : // textField_2
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_SNcodigo.getValue()));
                break;
            }
            case 2287 : // variable_TotalDoc
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotal.getValue()));
                break;
            }
            case 2289 : // variable_TotalMonedaLoc
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getValue()));
                break;
            }
            case 2273 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 2301 : // textField_5
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalMoneda.getEstimatedValue()));
                break;
            }
            case 2286 : // variableInitialValue_TotalCliente
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2302 : // textField_6
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalMonedaLoc.getEstimatedValue()));
                break;
            }
            case 2292 : // variableInitialValue_TotalDocLoc
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2285 : // variable_TotalCliente
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getValue()));
                break;
            }
            case 2268 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2297 : // variable_SNcodigo_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2282 : // variableInitialValue_test
            {
                value = (java.lang.String)("test");
                break;
            }
            case 2280 : // parameterDefaultValue_CCTcodigo
            {
                value = (java.lang.String)(new java.lang.String("-1"));
                break;
            }
            case 2284 : // variableInitialValue_TotalMoneda
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2312 : // textField_14
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotal.getValue()));
                break;
            }
            case 2277 : // parameterDefaultValue_fechaIniLabel
            {
                value = (java.lang.String)("Todas");
                break;
            }
            case 2305 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 2311 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)field_BMfecha.getValue()));
                break;
            }
            case 2313 : // textField_15
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotalloc.getValue()));
                break;
            }
            case 2296 : // textField_3
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalCliente.getEstimatedValue()));
                break;
            }
            case 2270 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 2315 : // textField_17
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " of ");
                break;
            }
            case 2307 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)parameter_fechaIniLabel.getValue()));
                break;
            }
            case 2310 : // textField_12
            {
                value = (java.lang.String)(((java.lang.String)field_Ddocumento.getValue()));
                break;
            }
            case 2309 : // textField_11
            {
                value = (java.lang.String)(((java.lang.String)field_tipo.getValue()));
                break;
            }
            case 2283 : // variable_TotalMoneda
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtotal.getValue()));
                break;
            }
            case 2314 : // textField_16
            {
                value = (java.lang.Double)(((java.lang.Double)field_Dtipocambio.getValue()));
                break;
            }
            case 2290 : // variableInitialValue_TotalMonedaLoc
            {
                value = (java.lang.Double)(new java.lang.Double("0.00"));
                break;
            }
            case 2317 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)field_fecha_hora.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
