/*
 * Generated by JasperReports - 06/07/04 03:20 PM
 */
import dori.jasper.engine.*;
import dori.jasper.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;


/**
 *
 */
public class depreciacionMes extends JRCalculator
{


    /**
     *
     */
    private JRFillParameter parameter_Ecodigo = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_Mes = null;
    private JRFillParameter parameter_Centro = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_Periodo = null;
    private JRFillParameter parameter_Categoria = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_nombMes = null;
    private JRFillParameter parameter_Clase = null;

    private JRFillField field_AFSdepacummej = null;
    private JRFillField field_AFSdepacumrev = null;
    private JRFillField field_Edescripcion = null;
    private JRFillField field_ACcodigodesc = null;
    private JRFillField field_CFdescripcion = null;
    private JRFillField field_ACdescripcion = null;
    private JRFillField field_categoria = null;
    private JRFillField field_AFSdepacumadq = null;
    private JRFillField field_clasedescripcion = null;
    private JRFillField field_CFid = null;

    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_totclaseadqdep = null;
    private JRFillVariable variable_totclasemejdep = null;
    private JRFillVariable variable_totclaserevdep = null;
    private JRFillVariable variable_totcatadqdep = null;
    private JRFillVariable variable_totcfadqdep = null;
    private JRFillVariable variable_totcatmejdep = null;
    private JRFillVariable variable_totcfmejdep = null;
    private JRFillVariable variable_totcatrevdep = null;
    private JRFillVariable variable_totcfrevdep = null;
    private JRFillVariable variable_totGendepacumadq = null;
    private JRFillVariable variable_totGendepacummej = null;
    private JRFillVariable variable_totGendepacumrev = null;
    private JRFillVariable variable_CFdescripcion_COUNT = null;
    private JRFillVariable variable_Categoria_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        ) throws JRException
    {
        parameter_Ecodigo = (JRFillParameter)parsm.get("Ecodigo");
        parameter_REPORT_CONNECTION = (JRFillParameter)parsm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)parsm.get("REPORT_PARAMETERS_MAP");
        parameter_Mes = (JRFillParameter)parsm.get("Mes");
        parameter_Centro = (JRFillParameter)parsm.get("Centro");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)parsm.get("REPORT_DATA_SOURCE");
        parameter_Periodo = (JRFillParameter)parsm.get("Periodo");
        parameter_Categoria = (JRFillParameter)parsm.get("Categoria");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)parsm.get("REPORT_SCRIPTLET");
        parameter_nombMes = (JRFillParameter)parsm.get("nombMes");
        parameter_Clase = (JRFillParameter)parsm.get("Clase");

        field_AFSdepacummej = (JRFillField)fldsm.get("AFSdepacummej");
        field_AFSdepacumrev = (JRFillField)fldsm.get("AFSdepacumrev");
        field_Edescripcion = (JRFillField)fldsm.get("Edescripcion");
        field_ACcodigodesc = (JRFillField)fldsm.get("ACcodigodesc");
        field_CFdescripcion = (JRFillField)fldsm.get("CFdescripcion");
        field_ACdescripcion = (JRFillField)fldsm.get("ACdescripcion");
        field_categoria = (JRFillField)fldsm.get("categoria");
        field_AFSdepacumadq = (JRFillField)fldsm.get("AFSdepacumadq");
        field_clasedescripcion = (JRFillField)fldsm.get("clasedescripcion");
        field_CFid = (JRFillField)fldsm.get("CFid");

        variable_PAGE_NUMBER = (JRFillVariable)varsm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)varsm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)varsm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)varsm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)varsm.get("COLUMN_COUNT");
        variable_totclaseadqdep = (JRFillVariable)varsm.get("totclaseadqdep");
        variable_totclasemejdep = (JRFillVariable)varsm.get("totclasemejdep");
        variable_totclaserevdep = (JRFillVariable)varsm.get("totclaserevdep");
        variable_totcatadqdep = (JRFillVariable)varsm.get("totcatadqdep");
        variable_totcfadqdep = (JRFillVariable)varsm.get("totcfadqdep");
        variable_totcatmejdep = (JRFillVariable)varsm.get("totcatmejdep");
        variable_totcfmejdep = (JRFillVariable)varsm.get("totcfmejdep");
        variable_totcatrevdep = (JRFillVariable)varsm.get("totcatrevdep");
        variable_totcfrevdep = (JRFillVariable)varsm.get("totcfrevdep");
        variable_totGendepacumadq = (JRFillVariable)varsm.get("totGendepacumadq");
        variable_totGendepacummej = (JRFillVariable)varsm.get("totGendepacummej");
        variable_totGendepacumrev = (JRFillVariable)varsm.get("totGendepacumrev");
        variable_CFdescripcion_COUNT = (JRFillVariable)varsm.get("CFdescripcion_COUNT");
        variable_Categoria_COUNT = (JRFillVariable)varsm.get("Categoria_COUNT");
    }


    /**
     * Test method
     */
    public static void helloJasper()
    {
        System.out.println("------------------------------");
        System.out.println(" Hello, Jasper!...");
        System.out.println("------------------------------");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1191 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1190 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1222 : // printWhen_38
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1146 : // variable_totclaseadqdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1221 : // textField_21
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1209 : // printWhen_31
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1168 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1194 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1202 : // printWhen_24
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1152 : // variable_totcfmejdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1136 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1205 : // printWhen_27
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1215 : // printWhen_34
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1226 : // printWhen_40
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1135 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1192 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getValue()));
                break;
            }
            case 1223 : // textField_22
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1149 : // variable_totcatadqdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1167 : // textField_4
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcfmejdep.getValue()));
                break;
            }
            case 1181 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getValue()));
                break;
            }
            case 1184 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1142 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 1228 : // printWhen_41
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1179 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1150 : // variable_totcfadqdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1164 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1137 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1218 : // printWhen_36
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1165 : // textField_3
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcfrevdep.getValue()));
                break;
            }
            case 1174 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_CFid.getValue()));
                break;
            }
            case 1133 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1159 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1163 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 1141 : // parameterDefaultValue_Mes
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(03));
                break;
            }
            case 1216 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)field_ACcodigodesc.getValue()));
                break;
            }
            case 1186 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1151 : // variable_totcatmejdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1235 : // printWhen_45
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1232 : // textField_26
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGendepacumadq.getValue()));
                break;
            }
            case 1189 : // textField_12
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatadqdep.getValue()));
                break;
            }
            case 1177 : // variableInitialValue_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1197 : // variableInitialValue_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1157 : // variable_totGendepacumrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1211 : // printWhen_32
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1225 : // textField_23
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 1187 : // textField_11
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatmejdep.getValue()));
                break;
            }
            case 1234 : // textField_27
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGendepacummej.getValue()));
                break;
            }
            case 1140 : // parameterDefaultValue_Periodo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(2002));
                break;
            }
            case 1236 : // textField_28
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGendepacumrev.getValue()));
                break;
            }
            case 1220 : // printWhen_37
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1172 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1227 : // textField_24
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " de ");
                break;
            }
            case 1196 : // variable_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1160 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1219 : // textField_20
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1231 : // printWhen_43
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1203 : // printWhen_25
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1148 : // variable_totclaserevdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1147 : // variable_totclasemejdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1193 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1170 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1201 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 1208 : // printWhen_30
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1158 : // group_CFdescripcion
            {
                value = (java.lang.Object)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 1155 : // variable_totGendepacumadq
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1214 : // textField_18
            {
                value = (java.lang.String)(((java.lang.String)field_clasedescripcion.getValue()));
                break;
            }
            case 1178 : // group_Categoria
            {
                value = (java.lang.Object)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 1138 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1169 : // textField_5
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcfadqdep.getValue()));
                break;
            }
            case 1199 : // printWhen_22
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1173 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1156 : // variable_totGendepacummej
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1153 : // variable_totcatrevdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1182 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1132 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1224 : // printWhen_39
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1217 : // printWhen_35
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1134 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1144 : // parameterDefaultValue_Categoria
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 1145 : // parameterDefaultValue_Clase
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 1204 : // printWhen_26
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1206 : // printWhen_28
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1162 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1195 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 1212 : // textField_17
            {
                value = (java.lang.String)(((java.lang.String)parameter_nombMes.getValue()));
                break;
            }
            case 1154 : // variable_totcfrevdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1229 : // textField_25
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
            case 1171 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 1233 : // printWhen_44
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1139 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1176 : // variable_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1210 : // textField_16
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_Periodo.getValue()));
                break;
            }
            case 1188 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1230 : // printWhen_42
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1161 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_CFid.getValue()));
                break;
            }
            case 1207 : // printWhen_29
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1213 : // printWhen_33
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1166 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1175 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1180 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1143 : // parameterDefaultValue_Centro
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 1185 : // textField_10
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatrevdep.getValue()));
                break;
            }
            case 1200 : // printWhen_23
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1198 : // printWhen_21
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) == null));
                break;
            }
            case 1183 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1191 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1190 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1222 : // printWhen_38
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1146 : // variable_totclaseadqdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getOldValue()));
                break;
            }
            case 1221 : // textField_21
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getOldValue()));
                break;
            }
            case 1209 : // printWhen_31
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1168 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1194 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1202 : // printWhen_24
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1152 : // variable_totcfmejdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getOldValue()));
                break;
            }
            case 1136 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1205 : // printWhen_27
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1215 : // printWhen_34
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1226 : // printWhen_40
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1135 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1192 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getOldValue()));
                break;
            }
            case 1223 : // textField_22
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getOldValue()));
                break;
            }
            case 1149 : // variable_totcatadqdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getOldValue()));
                break;
            }
            case 1167 : // textField_4
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcfmejdep.getOldValue()));
                break;
            }
            case 1181 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getOldValue()));
                break;
            }
            case 1184 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1142 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 1228 : // printWhen_41
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1179 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1150 : // variable_totcfadqdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getOldValue()));
                break;
            }
            case 1164 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1137 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1218 : // printWhen_36
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1165 : // textField_3
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcfrevdep.getOldValue()));
                break;
            }
            case 1174 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_CFid.getOldValue()));
                break;
            }
            case 1133 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1159 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1163 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getOldValue()));
                break;
            }
            case 1141 : // parameterDefaultValue_Mes
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(03));
                break;
            }
            case 1216 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)field_ACcodigodesc.getOldValue()));
                break;
            }
            case 1186 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1151 : // variable_totcatmejdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getOldValue()));
                break;
            }
            case 1235 : // printWhen_45
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1232 : // textField_26
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGendepacumadq.getOldValue()));
                break;
            }
            case 1189 : // textField_12
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatadqdep.getOldValue()));
                break;
            }
            case 1177 : // variableInitialValue_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1197 : // variableInitialValue_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1157 : // variable_totGendepacumrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getOldValue()));
                break;
            }
            case 1211 : // printWhen_32
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1225 : // textField_23
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 1187 : // textField_11
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatmejdep.getOldValue()));
                break;
            }
            case 1234 : // textField_27
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGendepacummej.getOldValue()));
                break;
            }
            case 1140 : // parameterDefaultValue_Periodo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(2002));
                break;
            }
            case 1236 : // textField_28
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGendepacumrev.getOldValue()));
                break;
            }
            case 1220 : // printWhen_37
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1172 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1227 : // textField_24
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " de ");
                break;
            }
            case 1196 : // variable_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1160 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1219 : // textField_20
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getOldValue()));
                break;
            }
            case 1231 : // printWhen_43
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1203 : // printWhen_25
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1148 : // variable_totclaserevdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getOldValue()));
                break;
            }
            case 1147 : // variable_totclasemejdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getOldValue()));
                break;
            }
            case 1193 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1170 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1201 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getOldValue()));
                break;
            }
            case 1208 : // printWhen_30
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1158 : // group_CFdescripcion
            {
                value = (java.lang.Object)(((java.lang.String)field_CFdescripcion.getOldValue()));
                break;
            }
            case 1155 : // variable_totGendepacumadq
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getOldValue()));
                break;
            }
            case 1214 : // textField_18
            {
                value = (java.lang.String)(((java.lang.String)field_clasedescripcion.getOldValue()));
                break;
            }
            case 1178 : // group_Categoria
            {
                value = (java.lang.Object)(((java.lang.String)field_ACdescripcion.getOldValue()));
                break;
            }
            case 1138 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1169 : // textField_5
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcfadqdep.getOldValue()));
                break;
            }
            case 1199 : // printWhen_22
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1173 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1156 : // variable_totGendepacummej
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getOldValue()));
                break;
            }
            case 1153 : // variable_totcatrevdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getOldValue()));
                break;
            }
            case 1182 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1132 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1224 : // printWhen_39
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1217 : // printWhen_35
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1134 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1144 : // parameterDefaultValue_Categoria
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 1145 : // parameterDefaultValue_Clase
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 1204 : // printWhen_26
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1206 : // printWhen_28
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1162 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1195 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getOldValue()));
                break;
            }
            case 1212 : // textField_17
            {
                value = (java.lang.String)(((java.lang.String)parameter_nombMes.getValue()));
                break;
            }
            case 1154 : // variable_totcfrevdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getOldValue()));
                break;
            }
            case 1229 : // textField_25
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
            case 1171 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getOldValue()));
                break;
            }
            case 1233 : // printWhen_44
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1139 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1176 : // variable_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1210 : // textField_16
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_Periodo.getValue()));
                break;
            }
            case 1188 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1230 : // printWhen_42
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1161 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_CFid.getOldValue()));
                break;
            }
            case 1207 : // printWhen_29
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1213 : // printWhen_33
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1166 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1175 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1180 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1143 : // parameterDefaultValue_Centro
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 1185 : // textField_10
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatrevdep.getOldValue()));
                break;
            }
            case 1200 : // printWhen_23
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) != null));
                break;
            }
            case 1198 : // printWhen_21
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getOldValue()) == null));
                break;
            }
            case 1183 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 1191 : // printWhen_18
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1190 : // printWhen_17
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1222 : // printWhen_38
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1146 : // variable_totclaseadqdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1221 : // textField_21
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1209 : // printWhen_31
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1168 : // printWhen_6
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1194 : // printWhen_20
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1202 : // printWhen_24
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1152 : // variable_totcfmejdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1136 : // variable_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1205 : // printWhen_27
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1215 : // printWhen_34
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1226 : // printWhen_40
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1135 : // variableInitialValue_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1192 : // textField_13
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getValue()));
                break;
            }
            case 1223 : // textField_22
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1149 : // variable_totcatadqdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1167 : // textField_4
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcfmejdep.getEstimatedValue()));
                break;
            }
            case 1181 : // textField_8
            {
                value = (java.lang.String)(((java.lang.String)field_categoria.getValue()));
                break;
            }
            case 1184 : // printWhen_14
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1142 : // parameterDefaultValue_Ecodigo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(1));
                break;
            }
            case 1228 : // printWhen_41
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1179 : // printWhen_11
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1150 : // variable_totcfadqdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1164 : // printWhen_4
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1137 : // variableInitialValue_PAGE_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1218 : // printWhen_36
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1165 : // textField_3
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcfrevdep.getEstimatedValue()));
                break;
            }
            case 1174 : // textField_7
            {
                value = (java.lang.String)(((java.lang.String)field_CFid.getValue()));
                break;
            }
            case 1133 : // variableInitialValue_COLUMN_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1159 : // printWhen_1
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1163 : // textField_2
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 1141 : // parameterDefaultValue_Mes
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(03));
                break;
            }
            case 1216 : // textField_19
            {
                value = (java.lang.String)(((java.lang.String)field_ACcodigodesc.getValue()));
                break;
            }
            case 1186 : // printWhen_15
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1151 : // variable_totcatmejdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1235 : // printWhen_45
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1232 : // textField_26
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGendepacumadq.getEstimatedValue()));
                break;
            }
            case 1189 : // textField_12
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatadqdep.getEstimatedValue()));
                break;
            }
            case 1177 : // variableInitialValue_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1197 : // variableInitialValue_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1157 : // variable_totGendepacumrev
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1211 : // printWhen_32
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1225 : // textField_23
            {
                value = (java.util.Date)(new Date());
                break;
            }
            case 1187 : // textField_11
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatmejdep.getEstimatedValue()));
                break;
            }
            case 1234 : // textField_27
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGendepacummej.getEstimatedValue()));
                break;
            }
            case 1140 : // parameterDefaultValue_Periodo
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(2002));
                break;
            }
            case 1236 : // textField_28
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totGendepacumrev.getEstimatedValue()));
                break;
            }
            case 1220 : // printWhen_37
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1172 : // printWhen_8
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1227 : // textField_24
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " de ");
                break;
            }
            case 1196 : // variable_Categoria_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1160 : // printWhen_2
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1219 : // textField_20
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1231 : // printWhen_43
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1203 : // printWhen_25
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1148 : // variable_totclaserevdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1147 : // variable_totclasemejdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1193 : // printWhen_19
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1170 : // printWhen_7
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1201 : // textField_15
            {
                value = (java.lang.String)(((java.lang.String)field_Edescripcion.getValue()));
                break;
            }
            case 1208 : // printWhen_30
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1158 : // group_CFdescripcion
            {
                value = (java.lang.Object)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 1155 : // variable_totGendepacumadq
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumadq.getValue()));
                break;
            }
            case 1214 : // textField_18
            {
                value = (java.lang.String)(((java.lang.String)field_clasedescripcion.getValue()));
                break;
            }
            case 1178 : // group_Categoria
            {
                value = (java.lang.Object)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 1138 : // variable_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1169 : // textField_5
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcfadqdep.getEstimatedValue()));
                break;
            }
            case 1199 : // printWhen_22
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1173 : // printWhen_9
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1156 : // variable_totGendepacummej
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacummej.getValue()));
                break;
            }
            case 1153 : // variable_totcatrevdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1182 : // printWhen_13
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1132 : // variableInitialValue_PAGE_NUMBER
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1224 : // printWhen_39
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1217 : // printWhen_35
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1134 : // variable_REPORT_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1144 : // parameterDefaultValue_Categoria
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 1145 : // parameterDefaultValue_Clase
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 1204 : // printWhen_26
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1206 : // printWhen_28
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1162 : // printWhen_3
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1195 : // textField_14
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
            case 1212 : // textField_17
            {
                value = (java.lang.String)(((java.lang.String)parameter_nombMes.getValue()));
                break;
            }
            case 1154 : // variable_totcfrevdep
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_AFSdepacumrev.getValue()));
                break;
            }
            case 1229 : // textField_25
            {
                value = (java.lang.String)(" " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
            case 1171 : // textField_6
            {
                value = (java.lang.String)(((java.lang.String)field_CFdescripcion.getValue()));
                break;
            }
            case 1233 : // printWhen_44
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1139 : // variableInitialValue_COLUMN_COUNT
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 1176 : // variable_CFdescripcion_COUNT
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1210 : // textField_16
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_Periodo.getValue()));
                break;
            }
            case 1188 : // printWhen_16
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1230 : // printWhen_42
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1161 : // textField_1
            {
                value = (java.lang.String)(((java.lang.String)field_CFid.getValue()));
                break;
            }
            case 1207 : // printWhen_29
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1213 : // printWhen_33
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1166 : // printWhen_5
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1175 : // printWhen_10
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1180 : // printWhen_12
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1143 : // parameterDefaultValue_Centro
            {
                value = (java.math.BigDecimal)(new java.math.BigDecimal(0));
                break;
            }
            case 1185 : // textField_10
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_totcatrevdep.getEstimatedValue()));
                break;
            }
            case 1200 : // printWhen_23
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) != null));
                break;
            }
            case 1198 : // printWhen_21
            {
                value = (java.lang.Boolean)(new Boolean(((java.lang.String)field_Edescripcion.getValue()) == null));
                break;
            }
            case 1183 : // textField_9
            {
                value = (java.lang.String)(((java.lang.String)field_ACdescripcion.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
